### ISSUE TITLE
Adding a logo to the docs

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#110]
Now that we've back on `alabaster`, we've got an empty hole in the top left where the logo usually goes. Do we want to:

1. Use the jupyter logo
2. Use the binder logo
3. Make a logo for repo2docker (maybe just something like below?)

![image](https://user-images.githubusercontent.com/1839645/31912975-9e32def0-b7fa-11e7-8a29-4e56c1984f1d.png)

?

**Comment by willingc** [comment]
Jupyter logo
