### ISSUE TITLE
requirements.txt and runtime.txt are not followed if environment.yaml is present

### ISSUE THREAD

**Issue by AaronWatters** [jupyter/repo2docker#113]
In https://github.com/simonsfoundation/regulatory_network_examples the requirements.txt
and runtime.txt were not being observed.  In https://github.com/simonsfoundation/jp_svg_canvas they are observed.  The only difference I can see is that https://github.com/simonsfoundation/jp_svg_canvas has a setup.py script.

I could work around by adding python=2 to environment.yml and adding
`pip install -r requirements.txt` to the postBuild script.

In my view these work arounds should not be needed.

**Comment by choldgraf** [comment]
one option to help you debug is to use the `--debug` and `--no-build` flags with repo2docker locally...this will print the dockerfile that r2d builds before creating an image. See the syntax for that here:

https://github.com/jupyter/repo2docker#usage

That said, IMO if you're using environment.yml, you should be using that file for pretty much all python dependencies. I could see how mixing env.yml and reqs.txt could create confusions and edge cases

**Comment by AaronWatters** [comment]
I tried to use the --debug and --no-build flags.  The output of the two builds were identical.

**Comment by choldgraf** [comment]
then...that is super weird :-)

If you're still debugging, feel free to paste the `--debug` output in this issue so we can take a look, though it sounds like the `pip:` field in `environment.yaml` fixed it?

**Comment by AaronWatters** [comment]
Here is the output (stderr and stdout)  the only difference between the two builds
is the last line currently.
```
[Repo2Docker] Looking for repo2docker_config in /Users/awatters/tmp/repo2docker

FROM buildpack-deps:zesty

 # Set up locales properly
RUN apt-get update && \
    apt-get install --yes --no-install-recommends locales && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

 # Use bash as default shell, rather than sh
ENV SHELL /bin/bash

 # Set up user
ENV NB_USER jovyan
ENV NB_UID 1000
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}
WORKDIR ${HOME}

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
       less \
       nodejs-legacy \
       npm \
       && apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

 # make JUPYTERHUB_VERSION a build argument
ARG JUPYTERHUB_VERSION=0.7.2

EXPOSE 8888

 # Almost all environment variables
ENV APP_BASE /srv
ENV CONDA_DIR ${APP_BASE}/conda
ENV NB_PYTHON_PREFIX ${CONDA_DIR}
# Special case PATH
ENV PATH ${CONDA_DIR}/bin:${PATH}
 # If scripts required during build are present, copy them

COPY conda/install-miniconda.bash /tmp/install-miniconda.bash

COPY conda/environment.yml /tmp/environment.yml
RUN bash /tmp/install-miniconda.bash && \
rm /tmp/install-miniconda.bash /tmp/environment.yml



 # Copy and chown stuff. This doubles the size of the repo, because
 # you can't actually copy as USER, only as root! Thanks, Docker!
USER root
COPY src/ ${HOME}
RUN chown -R ${NB_USER}:${NB_USER} ${HOME}

 # Run assemble scripts! These will actually build the specification
 # in the repository into the image.
USER ${NB_USER}
RUN conda env update -n root -f "environment.yml" && \
conda clean -tipsy



 # Container image Labels!
 # Put these at the end, since we don't want to rebuild everything
 # when these change! Did I mention I hate Dockerfile cache semantics?


 # We always want containers to run as non-root
USER ${NB_USER}

RUN ./postBuild

```

**Comment by Carreau** [comment]
You have an `environement.yml` file, thus we use conda. If you need extra requirement not available with conda I believe you need to use the `pip:` section of `environment.yml`

I think it looks like the requiremetn.txt of svg_canavas looks to be observed, is that they are all dependencies of ipywidget, which is not the case for regulatory_network_examples. 

I may be wrong.

**Comment by AaronWatters** [comment]
Ok, I'm fine with not using requirements.txt if you have environment.yml as long as the restriction is documented.  I find it confusing to have runtime.txt not work sometimes (even though there is an easy work around).

**Comment by betatim** [comment]
👍 on documenting this. The docs make a point of mentioning composability which made me think that you can use `environment.yml` and `requirements.txt` and `apt-get` all together (with some well defined order of execution). I think we should add two sections to the docs:

1. which build packs can be combined and which can't
1. in which order build packs are applied

**Comment by choldgraf** [comment]
FWIW I feel like it wouldn't be that hard to use both `environment.yml` and `requirements.txt`, no? You'd just need to source activate the conda environment before you ran the pip install commands.

**Comment by Carreau** [comment]
> FWIW I feel like it wouldn't be that hard to use both environment.yml and requirements.txt, no? You'd just need to source activate the conda environment before you ran the pip install commands.

I think it would make sens though `There should be one-- and preferably only one --obvious way to do it.`. And from experience using conda + pip without the pip section of env.yml lead to trouble when installing-uninstalling packages. I'd like to not encourage behavior in binder that would lead to trouble when used  locally. 

If we do a reproducibility badge we  could add a lint rule that detect requirements.txt and env.yml and display a warning.

**Comment by choldgraf** [comment]
or we could error on detection of *both* environment.yml and reqs.txt. I foresee people getting confused over this since it's a bit hard to catch in the logs (esp since they don't persist after the binder is built). If we had an informative error message telling people to use the `pip:` field maybe that'd help

**Comment by willingc** [comment]
@choldgraf Do you think #165 closes this issue?

**Comment by choldgraf** [comment]
yep!
