### ISSUE TITLE
Make it clear that this can't be used to build arbitrary dockerfiles for personal use

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#114]
We've had a few people try to use repo2docker as a quick way to build a Dockerfile that they copy/paste for their own use. This isn't supported and we should make that clear in the docs...

**Comment by yuvipanda** [comment]
Partially fixed by https://github.com/jupyter/repo2docker/pull/117

We should put a prominent link to FAQ in places!

**Comment by willingc** [comment]
Closing as resolved by #117 and #165
