### ISSUE TITLE
Make it clear that windows support is experimental

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#125]
Windows behaves very differently with lots of the commands that repo2docker uses...I don't think it'll work right now (running it on my machine just makes it hang when in windows).

**Comment by betatim** [comment]
Some things to check:

* [ ] use `os.path.sep` everywhere instead of `/`
* [ ] `os.path.join` to construct paths
* [ ] `/tmp` probably doesn't exist, use `tempfile`??

**Comment by willingc** [comment]
@choldgraf @betatim Close?

**Comment by choldgraf** [comment]
I'm not quite sure on this one, I gave up on Docker for Windows and just started dual-booting Ubuntu :-)

when I get a moment I can test again on Windows, though it may be a bit futile as IME Docker for windows is not the same experience on Docker for *nix

**Comment by willingc** [comment]
I would forgo formal support and make support similar to JupyterHub (*nix supported; Windows YMMV so not officially supported). Posting [this article](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) as a reference for others using Windows and WSL (Windows Subsystem Linux).

**Comment by choldgraf** [comment]
Good idea - I'm going to change this issue title to match the new plan

**Comment by choldgraf** [comment]
so, what if we added a check for `sys.platform` and if it was `win*` then we throw a warning about non-guaranteed windows support.
