### ISSUE TITLE
Investigate spurious travis timeouts to improve travis config

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#127]
Currently travis goes red for reasons that are unrelated to the changes proposed in a PR. This makes it hard to know if the changes broke something or it is just "a random failure". It also trains us to click merge when travis is red because "that is an unrelated failure..." when actually it isn't.

The first step would be to identify common failures-that-aren't-real-failures. Step two would be to try and improve on them.

Maybe we can link to this issue or post build logs here that failed for "random reasons" to get started on step 1.

**Comment by yuvipanda** [comment]
Travis has been going bust for me on almost all the projects I'm working on, in ways I can't fix:

1. Pulling from dockerhub fails with a timeout
2. It just takes forever to start the travis build on travis side

I don't know what we can do to fix these though. I definitely saw a bunch of repo2docker errors that were (1)

**Comment by betatim** [comment]
https://docs.travis-ci.com/user/common-build-problems/#travis_retry might help for retrying things?

I've also seen a bunch of failures like (1). Manually restarting the build seems to fix it (sometimes). Can we run `docker pull` at the start of the job first? That might make it easier to spot that it is the pull that failed.

**Comment by willingc** [comment]
Changing the title of this issue to be more actionable. 

### General Process when Travis fails (red)

1. Review build log for test failures, job timeouts.
2. Restart the start of the job that fails manually.
3. If it fails continues to fail due to spurious, intermittent, timeouts, or nonspecific issues, raise the failure as a new issue (including a link to the build log and a snippet of the failure log message).

@betatim How often are you seeing timeout errors? If most runs, then we should give `travis_retry` a shot.

We may also wish to reorder the language command to come after the sudo and services in the Travis config.yml.

**Comment by betatim** [comment]
> How often are you seeing timeout errors?

Not sure really, often enough that when looking at PRs to merge I started thinking "ok, gotta have a chunk of time because red travis means I have to go check if it is really broken or just needs restarting".

One downside of `travis_retry` is that we waste resources and have to wait longer to get a decision when the build really is broken.

**Comment by willingc** [comment]
Any status updates on this? Is this an issue that we are resolving across repos? or is there something more specific to this repo?

**Comment by betatim** [comment]
No news from my side, mostly because I've not been making PRs :-/

**Comment by choldgraf** [comment]
didn't @yuvipanda do some travis stability work recently? Any of that touch on this?

**Comment by yuvipanda** [comment]
That was on z2jh :)

Repo2docker Travis has been stable for me for a while I think.

**Comment by willingc** [comment]
Let's close this issue for now. @betatim feel free to reopen again if needed.

**Comment by yuvipanda** [comment]
@willingc as a side note, I was curious about your comment 'We may also wish to reorder the language command to come after the sudo and services in the Travis config.yml.' so did some digging. AFAICT, it is just parsed as an unordered dictionary, so ordering doesn't seem to matter. Can you expand a tiny bit on what you meant by that? sudo is one of the reasons our tests take long, and it'd be great if there was some feature we can use to change that...
