### ISSUE TITLE
Copy repo contents to a subdirectory

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#129]
Is there a reason to copy the repo into `/home/jovyan` or could we equally well copy it to `/home/jovyan/repo`?

I'd like to be able to mount a local directory into the container instead of copying the repository but currently that also wipes out all the hidden files in the home directory.

**Comment by yuvipanda** [comment]
Does --editable solve this use case?

**Comment by betatim** [comment]
Probably. And if not I don't remember enough about the original use-case to be able to write more. Closing.
