### ISSUE TITLE
shim for current binder's Dockerfiles

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#13]
People running the Dockerfile builder for binder inherit `FROM andrewosh/binder-base`. These Dockerfiles will lack jupyterhub, but otherwise should work. If we add an `oldbinder-dockerfile` builder that detects Dockerfile and this FROM, we should be able to append the bits needed to work.

**Comment by yuvipanda** [comment]
I think we should just write a special-case BuildPack for this

**Comment by yuvipanda** [comment]
Let's close this after we deploy.

**Comment by yuvipanda** [comment]
@minrk I deployed this to staging, but it still errors with not being able to find jupyterhub-singleuser in $PATH.

**Comment by minrk** [comment]
what repo?

**Comment by yuvipanda** [comment]
https://github.com/binder-project/example-dockerfile

**Comment by yuvipanda** [comment]
@minrk got most of this working!

I also added a test for it (and got it working again after breaking it) in #43
