### ISSUE TITLE
--ref does not understand branch names

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#135]
I had assumed that `--ref` would also take a branch name or a tag, however it fails with the following error:
```
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.
fatal: ambiguous argument 'other-branch': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Failed to check out ref other-branch
```

**Comment by betatim** [comment]
Could fix this by runnint `git rev-parse <ref>` before https://github.com/jupyter/repo2docker/blob/88f7b34fedbb0780c66613d1c73d680c33678622/repo2docker/app.py#L106

**Comment by yuvipanda** [comment]
hmm, on my local git `git reset --hard master` works fine, but repo2docker fails. Strange!

**Comment by yuvipanda** [comment]
aaha, I think for git reset --hard <ref> it perhaps needs to be 'origin/branchname' rather than just branchname?

**Comment by yuvipanda** [comment]
git checkout is perhaps the better thing to use here. I switched to using git reset --hard because git checkout puts a long explanatory message that confuses users when used in our context. Perhaps we can switch back to using it but somehow hide that message?

**Comment by hydrosquall** [comment]
I wonder if this might be related to https://github.com/jupyterhub/binderhub/issues/263

**Comment by betatim** [comment]
To reproduce the above error you don't need binderhub, it happens when you call `repo2docker` from the command line. So I don't think it has anything to do with binderhub.

**Comment by brooksambrose** [comment]
Ran into this and `--ref origin/branchname` works; should it be documented?

**Comment by willingc** [comment]
Good suggestion @brooksambrose. Labeling this issue for documentation. Please feel free to submit a PR if you have time. Thanks.
