### ISSUE TITLE
Make a v0.4.2 release

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#136]
Someone should make a release and point that as new default in https://github.com/jupyterhub/binderhub/blob/master/binderhub/app.py#L158.

We should also use this as an opportunity to make sure that everyone has permissions on PyPI and the release process is documented.

**Comment by choldgraf** [comment]
I can do this in the next couple of days, though it may make sense for somebody else to do this so we increase the bus factor by more...maybe @betatim wants to help w/ this? Or we can do it at the same time

**Comment by betatim** [comment]
I'll give this a crack now.

**Comment by betatim** [comment]
Instead of doing any work, below the tasks that I think need doing.

Pre-release checklist (only needs doing this time):
* [ ] email account
* [ ] PyPi account for r2d
* [ ] configure travis to deploy on tag [docs](https://docs.travis-ci.com/user/deployment/pypi/) [example](https://github.com/scikit-optimize/scikit-optimize/blob/be5f87aab8d61d8bee123340715716bfd9506a3c/.travis.yml#L30-L41)

Release checklist (every release):
* [ ] all PRs merged?
* [ ] bump version in `setup.py`
* [ ] bump version in `repo2docker/__init__.py`
* [ ] [Draft a new release](https://github.com/jupyter/repo2docker/releases)
* [ ] wait for travis and then check PyPi
* [ ] Party!

Post release:
* [ ] [update binderhub builder image spec](https://github.com/jupyterhub/binderhub/blob/7a2b134652e19eaccc209e50358607bdda2bfd9b/binderhub/app.py#L158)
* deploy mybinder (??)

**Comment by betatim** [comment]
@choldgraf can you hook us up with an email address that forwards emails to "everyone"? Once that is in place I'll take care of PyPi etc

**Comment by choldgraf** [comment]
Hmmm, what do you think is the best way to do this? Use something like
`dev@mybinder.org`?
--

**Comment by yuvipanda** [comment]
I don't think we want to host any email servers under mybinder.org. So it'd be something like projectbinder@gmail.com. Perhaps a Google Group set as a 'common inbox'?

**Comment by choldgraf** [comment]
That works for me.

**Comment by Carreau** [comment]
Note that there is an issue on warehouse (aka PyPI-next) to have upload token or equivalent to not have to create an account "just" for a package. Maybe we should consider writing that patch to warehouse ?

**Comment by betatim** [comment]
That would be pretty cool. I had a look around their issues but couldn't find it, do you have a issue number to link?

I assume writing this feature would take more than an hour or two which means getting it merged and deployed will take quite a while. Should we go ahead for the next release using an account and then switch over later?

**Comment by betatim** [comment]
projectbinder@gmail.com is already taken, I assume that was you @choldgraf ? Can you also create the PyPi account or set the email account up so it forwards stuff.

**Comment by choldgraf** [comment]
sadly no :-/  `binderproject@` is also taken. I tried looking for a binder of permutations of Binder / project / community / team but had a hard time finding an available handle :-/

**Comment by choldgraf** [comment]
there is *mybinderproject* available...

**Comment by choldgraf** [comment]
@betatim now that we have a mybinderteam email, do you want me to share access w/ you? If you use lastpass I can share the password so you can log in that way. Otherwise I can give you the password in some other fashion that will not terrify @yuvipanda :-D

**Comment by willingc** [comment]
A friendly bump. Do we still want to do 0.4.2 release? Or did we do it and forget to tag?

**Comment by yuvipanda** [comment]
I'm manually going to make a v0.5 release soon, since we've merged a lot of changes since. I'm happy for others to continue building deploy tooling for automatic releases, but IMO these releases are infrequent enough to be done manually for now. When I opened the issue I assumed someone is just going to do a manual release, rather than spend lots of effort trying to automate them :) however, others here probably have more experience running an actual community of OSS projects, so I'll defer to y'all around automating releases!

**Comment by yuvipanda** [comment]
soon -> in the new year :)

**Comment by willingc** [comment]
Let's hold off until 0.5 for releases. if we can. Let's set a date for 3 people to be around when @yuvipanda merges manually so that we can follow the manual process and hopefully document more thoroughly.

**Comment by willingc** [comment]
@yuvipanda If the consensus now is that we go to 0.5 next, let's close this one.
