### ISSUE TITLE
Is it possible to run a Dockerfile that uses Python2?

### ISSUE THREAD

**Issue by hydrosquall** [jupyter/repo2docker#139]
I've made an attempt here:

https://github.com/hydrosquall/pandas-cookbook/blob/feature-deploy-to-binder/binder/Dockerfile

The base image tag that I use stays with python 2, per the directions here: https://github.com/jupyter/docker-stacks

However, the launched notebook is still running python 3.6.

On a separate note, the instructions about making a custom dockerfile say that you should make a custom NB_USER, but that won't work as it just throws an error since that NB_USER ID has been hardcoded into mybinder already when deploying on mybinder.org.

**Comment by hydrosquall** [comment]
Hm, it looks like that base image creates python2 only in a virtual environment, and I don't see a way to tell repo2docker to use a particular virtualenv when launching the Jupyter server. Presently looking to see whether I can just use a different base image, or if I can adapt the example below.

https://github.com/binder-examples/python2_runtime

**Comment by hydrosquall** [comment]
After trying a bunch of different options, I finally got this to work:

- https://github.com/hydrosquall/pandas-cookbook/tree/feature-deploy-to-binder

With that said, this stops working if `runtime.txt` and `requirements.txt` are both under the `binder/` folder, so I had to get rid of the `binder/` folder and put both text files in the project root. 

It also doesn't work if just `runtime.txt` is in the root and `requirements.txt` is in the `binder/` folder, since it will fail to install the python2 kernel.

I also had to rename the default Dockerfile since that one is incompatible with deployment to `mybinder.org`.

Hope this helps anyone else who has the need to deploy Python2 examples on mybinder.org!

**Comment by choldgraf** [comment]
This is a bunch of good information, thanks for being thorough! I'm curious about debugging the Dockerfile problem, since technically your solution wasn't what you wanted to do (use python 2 with a dockerfile). That said, if you're fine w/ the `runtime.txt` approach then it also looks like there are other bugs you may have surfaced (e.g. it should behave the same way if they're in a `binder` folder compared w/ being in the root dir

**Comment by hydrosquall** [comment]
@choldgraf : the issue with the original Dockerfile that I wanted is that the base image I was looking has python 2, except that's hidden inside a `virtualenv`. I wasn't sure about how to activate that virtualenv using a `postBuild` script, since even if I "sourced" the virtualenv, wouldn't be active when `app.py` launches the `jupyter` command since each command is run in its own Docker container. Maybe adding a appending a `activate python2` command to the `.bashrc` or similar startup shell file could work, but I didn't have time to try it.

In any event, the `runtime.txt` bug is definitely there.

**Comment by betatim** [comment]
@hydrosquall so now you use a `runtime.txt` and `requirements.txt` and don't need a custom Dockerfile anymore?

**Comment by hydrosquall** [comment]
@betatim : for this particular notebook set, no custom `Dockerfile` was needed, correct :)!

**Comment by betatim** [comment]
I'll close this then, moved the su-dir bug into its own issue.
