### ISSUE TITLE
runtime and requirements in `binder/` doesn't work

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#141]
via @hydrosquall in #139:

> With that said, this stops working if `runtime.txt` and `requirements.txt` are both under the `binder/` folder, so I had to get rid of the `binder/` folder and put both text files in the project root. 
>
> It also doesn't work if just `runtime.txt` is in the root and `requirements.txt` is in the `binder/` folder, since it will fail to install the python2 kernel. This might be a bug worth investigating separately.

**Comment by betatim** [comment]
Kinda of related to this: if you have a `requirements.txt` in the top level directory, and `binder/postBuild` your requirements file will be ignored. Not sure if this is a feature or a bug

**Comment by willingc** [comment]
@choldgraf @betatim @yuvipanda I think we discussed documenting the build order and workflow (if file, then...). I can't remember if we did do that so am labeling this a docs issue for now.

**Comment by choldgraf** [comment]
the original bug should be fixed I believe, and from a documentation standpoint we mention a bit of this here now: http://repo2docker.readthedocs.io/en/latest/usage.html#preparing-your-repository

though there is no explicit "build order" section

**Comment by choldgraf** [comment]
This will be fixed in #277 I believe - we had a hard-coded path to a requirements file that was *only* in the Python2 buildpack, so would only be uncovered if people **both** had 2.7 specified in runtime.txt *and* used a `binder/` folder

**Comment by betatim** [comment]
Fixed by #277.
