### ISSUE TITLE
Pin jupyterlab to 0.28.*

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#154]
We recently ran into an issue where Jupyterlab and the jupyterlab_launch became incompatible. I think one reason this happened is that a patch was made in jupyterlab (0.28.9) whereas jupyterlab was pinned to (0.28) and this caused the bug to surface. What if we baked in `jupyterlab==0.28.*` instead of just 0.28 so that we get patch updates?

**Comment by jasongrout** [comment]
Similarly, we fixed a few small bugs in ipywidgets 6.0.1, so it's probably a good idea to accept ipywidgets 6.0.x releases as well.

**Comment by yuvipanda** [comment]
I think pinning to a * will go against the [deterministic output](https://github.com/jupyter/repo2docker/blob/master/docs/source/design.md#deterministic-output) design principle. Users would have no way of knowing which version is in a particular cached image, and no way to change it without making a new commit in the git repo.

We should pin it whenever there are new releases though. Perhaps a bot can automate watching pypi / conda for this?

**Comment by choldgraf** [comment]
I guess in this case I'm imagining *only* doing it for packages where we know the behavior of the release cycles. (e.g. jupyterlab or ipywidgets). but I agree this makes it less deterministic. Though FWIW the reason we found this bug is because the version of another plugin changed so it'll be hard to reach perfect determinism either way...

Otherwise, we could try to capture these issues with documentation, e.g. "if you want to use the latest version of jupyter lab, include it in your `requirements.txt` file"

**Comment by yuvipanda** [comment]
@choldgraf in those cases it should be easier for us to bump and not harder no? If JupyterLab 0.28 had a problem and 0.28.9 did not, and if we did '0.28.*' then images could have anywhere between JupyterLab 0.28.1 (which has some bug perhaps) and 0.28.9. And we would have no way to tell...

**Comment by jasongrout** [comment]
Agreed that it's definitely a trade-off between reproducibility and bugfixes. But since you are only pinning the top-level dependency, you didn't have reproducibility anyway - the problem here is that jlab depended on jupyterlab_launcher, but an update to jupyterlab_launcher is now breaking things.

If you are serious about the deterministic output, you should adopt a lock file model that pins *every* thing that is installed.

**Comment by jasongrout** [comment]
(see yarn or cargo's lock files, e.g., use something like pip freeze to pin every single thing installed - with md5 hashes for extra assurance)

**Comment by yuvipanda** [comment]
ah, hmm, interesting. Doesn't JupyterLab pin its own dependencies though? Am confused if installing Jupyterlab==<some-version> can produce broken versions now and then.

But I do agree that we should move towards full pinning!

**Comment by jasongrout** [comment]
jlab doesn't pin its dependencies exactly.

jlab 0.28 required jlab_launcher >=0.5.2 (https://github.com/jupyterlab/jupyterlab/blob/v0.28.0/setup.py#L115), but jlab_launcher 0.6.0 is incompatible, so jlab 0.28.9 fixed the version to be <0.6.0. Since you have 0.28.0, you get jlab_launcher 0.6.0, which is causing the problem.

**Comment by jasongrout** [comment]
(CC @blink1073 FYI)

**Comment by yuvipanda** [comment]
Ah, hmm. That all makes sense to me as a valid thing for a lot of packages to do! 

I think the pip freeze solution makes sense for requirements.txt. Is there a similar mechanism for conda we can use?

**Comment by jasongrout** [comment]
`conda env export` is the equivalent: https://conda.io/docs/user-guide/tasks/manage-environments.html#exporting-the-environment-file

**Comment by yuvipanda** [comment]
@minrk should I open a new issue for freezing environment.yml file?

**Comment by blink1073** [comment]
We had put out patch releases of 0.28 and 0.27 so we could make a breaking change to `jupyterlab_launcher`, but it seems the fix was not enough in this case.

**Comment by choldgraf** [comment]
well in this case the fix wasn't enough because we weren't installing the fixes :-)
