### ISSUE TITLE
Alpine Linux, pip/python & symlinks together break our build

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#160]
As part of #159, there's a symlink now in the test suite, since postBuild scripts for both the memorylimit tests are the same. However, this seems to break shutil on alpine. There's more discussion here: https://github.com/docker-library/python/issues/155 and https://github.com/python/cpython/pull/4267. Most likely because of musl vs libc issues.

This breaks the 'deploy' step, since our docker image no longer builds.

**Comment by betatim** [comment]
To get deploys working again I'd propose to duplicate the `postBuild` script. Once we have this deployed and are happy with the memlimiting we can take our time to decide if we want to change based image or what.

**Comment by yuvipanda** [comment]
I agree! am working on a PR now.

**Comment by willingc** [comment]
@yuvipanda Does #161 close this?

**Comment by yuvipanda** [comment]
It works around it for now, the underlying problem is still unfixed tho

**Comment by yuvipanda** [comment]
We moved away from alpine linux completely in 379c52bac3ab796cd945b3457295b3b4c3f9c6b6, so we can close this now.
