### ISSUE TITLE
Allow use of Git Large File Storage

### ISSUE THREAD

**Issue by suchow** [jupyter/repo2docker#162]
Git is an imperfect tool for handling large files, and so [Git Large File Storage](https://git-lfs.github.com/) (GLFS), an extension to Git, was developed. GLFS stores a small text file with a pointer to a larger file stored elsewhere, easing the burden on Git. A Git client with the GLFS extension installed will automatically download the large files when a repository is cloned.

Binder does not have GLFS installed. Thus when you clone a repository that uses GLFS, you get pointers to the data, not the data.

Here is an example repository:

https://github.com/suchow/binder-glfs

I propose that you install GLFS and use it when cloning the repository from GitHub.

If someone could point me towards the step where the repository is cloned, etc., I could take a stab at this and open a PR.

**Comment by suchow** [comment]
Given that this uses `git clone` under the hood,

https://github.com/jupyter/repo2docker/blob/2d31649d02d91f5e623006fbae0396632bfb5a63/repo2docker/app.py#L106

adding this feature may be as simple as installing GLFS on whatever machine generates the Docker image.

**Comment by suchow** [comment]
Closing this in light of https://github.com/jupyterhub/binderhub/issues/324.

**Comment by betatim** [comment]
You could install GLFS as part of the build and give users the option of turning the pointers into files at runtime. So only files they actually really wanted would be resolved/downloaded. Would that work?

If you want to host scientific data then maybe checkout osf.io and https://github.com/osfclient/osfclient which I worked on in the past.
