### ISSUE TITLE
Permission denied when trying to use image built by repo2docker

### ISSUE THREAD

**Issue by AaronWatters** [jupyter/repo2docker#171]
I've built a repository using repo2docker and the image that launches automatically works.
I want to use the built image again (with different flags passed to `docker run` for example).  When I try I see this

```bash
$ docker run -it --rm -p 8888:8888 r2d-2fusers-2fawatters-2frepos-2fcanine-5fbc-2f1513701909:latest
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

How can I use the image with the image without rebuilding it?

PS: This works:
```bash
$ docker run -it --rm -p 8888:8888 r2d-2fusers-2fawatters-2frepos-2fcanine-5fbc-2f1513701909:latest bash
```
for what it's worth (I'm still pretty much a novice with Docker and related concepts).

**Comment by AaronWatters** [comment]
I figured this out myself.  Apparently the default run command in the image is not the jupyter command.  When I give the jupyter command explicitly
```bash
$ docker run -it --rm -p 8888:8888 \
    r2d-2fusers-2fawatters-2frepos-2fcanine-5fbc-2f1513701909:latest \
    jupyter notebook --ip 0.0.0.0
```
it works.  So I guess I would like the default run command to be specified
to be `jupyter notebook` by the docker build.

**Comment by betatim** [comment]
There doesn't seem to be a good reason for not having a default command like you proposed.

Do you want to make a PR that adds a `CMD` to the dockerfile template we have?

**Comment by AaronWatters** [comment]
@betatim : #176

**Comment by willingc** [comment]
Closing this. Thank you @AaronWatters for the PR and for closing this issue. 👍
