### ISSUE TITLE
Consider installing requirements.txt into both python2 and python3 envs when runtime.txt specifies python2

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#173]
@mseal was discussing how it's confusing to have a requirements.txt and a requirements3.txt in a repo under the following circumstances:

1. You have a repo with mixed python3 *and* python2 code, so you need dependencies in python2 and 3
2. This requires you have a requirements.txt for python2 and a requirements3.txt for python3
3. If you need the same libraries on python3 and python2, you have to copy/paste requirements.txt and requirements3.txt

In this case, the repo maintainer has to keep these two in sync. That's not good.

So @mseal's proposal was to install requirements.txt into both py3 and py2 environments by default.

**Comment by yuvipanda** [comment]
I think however, that most common use case is that a repo needs a python2 env *or* a python3 env, rather than a python2 *and* python3 env. In that case, if we install requirements.txt into both envs by default, we end up slowing down installs and increasing size of image for the common case. We also have the possibility that requirements.txt will have a py2 only or py3 only dependency that'll break the build.

**Comment by choldgraf** [comment]
I'm +1 on the default being only one, and having the user explicitly ask
for the other. I agree the current workflow is a bit clunky but it seems
reasonable to me as long as it's well documented
