### ISSUE TITLE
Fix volume argument check when --no-build is given

### ISSUE THREAD

**Issue by mukundans91** [jupyter/repo2docker#178]
When --no-build argument is given along with -v argument, repo2docker must exit with error instead,
it accepts the volume definition

Need to check against the instance attribute run instead of args.run

**Comment by betatim** [comment]
Why can't I mount volumes when not building? It seems like providing volume mounts when not building isn't a mistake, just a no-op?

**Comment by mukundans91** [comment]
We can only mount volumes when a container is supposed to be run. Without that, we cannot mount volumes. As far as I saw from the previous post , I can see that the -v argument in repo2docker is only for mounting volumes. Shouldn't we tell the users that specifying -v when not running is incorrect ? As it was done with the no-run.

**Comment by choldgraf** [comment]
PR is welcome, was this a frustrating use-case for you? I'm not sure how many people we have both trying to mount drives and debug in a way that will be frustrating for them

**Comment by yuvipanda** [comment]
I agree, for correctness we should totally fail when no-build is given. Would welcome a PR, @mukundans91!
