### ISSUE TITLE
document and/or automate updating frozen environments

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#188]
Right now, to update the base environments, we need to:

1. (optional) update the base environment files:
    - buildpacks/conda/environment.yml
    - buildpacks/conda/environment.py-2.7.yml
    - buildpacks/py/requirements.txt
    - buildpacks/py/requirements2.txt
2. regenerate the frozen environments
    - `cd buildpacks/py && bash freeze.bash`
    - `cd buildpacks/conda && python freeze.py`

This requires:

- Python 3.6 (for the conda freeze script)
- Docker (for running the freezes)

We should at least document the process for contributors who want to bump the base env, and potentially automate it somehow if we can.

**Comment by choldgraf** [comment]
now documented in https://github.com/jupyter/repo2docker/blob/master/CONTRIBUTING.md#updating-libraries-installed-for-all-repos
