### ISSUE TITLE
Bump base distro after every new release until next LTS

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#198]
The next Ubuntu Release (Bionic) is an LTS release supported for a long time. When it comes out, we should bump the default to it, and then just let it be there until the next LTS gets released. This helps prevent issues like #197

**Comment by willingc** [comment]
Release schedule for Bionic Beaver: https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

Project release is end of April 2018.

**Comment by choldgraf** [comment]
we just merged in #302 so I'm closing this! Yay!
