### ISSUE TITLE
the Dockerfile is not enough to generate the image

### ISSUE THREAD

**Issue by natbusa** [jupyter/repo2docker#202]
Hi all,

for my ci/cd pipeline I am breaking down the image generation in two parts:
 - Generate the Dockerfile with :

```
jupyter-repo2docker --no-build --debug --user-id 1000 --user-name jovyan --image $IMAGE:$VERSION . 2> dockerfile.tmp
sed -n -e '/FROM/,$p' dockerfile.tmp > Dockerfile
cat Dockerfile
rm dockerfile.tmp
```
- Generate the image

while running the `docker build .` command on the generated Dockerfile, I see that it stumbles on 
```
COPY failed: stat conda/install-miniconda.bash: no such file or directory
```

Of course these files are available as part of the jupyter-repo2docker install, but not in the project directory.

The expected behaviour should be that `--no-build` generates all the necessary files in the current directory to produce a successful `docker build . `

**Comment by yuvipanda** [comment]
Thank you for opening the issue, @natbusa! 

Te dockerfile output is present only for debug purposes (it is generated by `--debug` rather than `--no-build`). We copy arbitrary ancillary files into the tarball that is sent to docker (see https://github.com/jupyter/repo2docker/blob/master/repo2docker/buildpacks/base.py#L210 and similar), so these won't be supported outside of repo2docker. I can not think of a clean way to generate a Dockerfile that is usable outside of repo2docker, so I don't think this will be a supported use case...

However, I realize that our docs on this are misleading, so I've opened a PR cleaning it up!

**Comment by natbusa** [comment]
I understand, however there might be a clean way to do so, by generating the files in the binder directory and having the Dockerfile only looking at the binder directory during build. This also has the advantage of being able to "capture" this files in a commit in case someone would like to reproduce the image without using repo2docker.

**Comment by natbusa** [comment]
sketch of the solution:
have a directory in binder called `builderpacks`

try the following dir structure:
```
  - binder
     - builderpacks
          - conda
          - python
          - etc..
```

**Comment by yuvipanda** [comment]
@natbusa would welcome a PR! Here are my (non-code) related worries about such a feature:

1. The Dockerfiles we generate are optimized for caching when repo2docker is being continuously run against multiple repos, so it won't be the most elegant or understandable when used standalone
2. We build from scratch all the time, while for most repositories that have a Dockerfile inheriting from a well known Docker image (for conda, julia, venv, etc) is probably a better fit
3. People might ask us for support about modifying the Dockerfile to fit their specific use case, which isn't something we are able to provide.

I think if we set expectations very clearly, we can add this as a feature behind another flag.

**Comment by yuvipanda** [comment]
@choldgraf https://github.com/jupyter/repo2docker/issues/202#issuecomment-362226734 has a list of problems, but it's unclear to me if a solution exists that solves these problems. So am not sure what to do here.

**Comment by choldgraf** [comment]
@natbusa given the challenges that @yuvipanda laid out, what do you think about this issue? Worth giving it a shot? (and if so, would you be willing to give a PR a shot) 

If it seems like this is too far outside the scope of r2d, I think we should close this issue and see if the problem pops up again.

**Comment by betatim** [comment]
I think we should improve the docs (if #205 isn't good enough) and then close this. I am -1 on officially supporting `repo2docker` as tool to generate template `Dockerfiles`.

**Comment by choldgraf** [comment]
@betatim I think that's fair. For now let's say it is "out of scope", and we can revisit this idea later if it seems to be a recurring roadblock for people...I'm going to close this issue, but if anybody would like to re-open for discussion, this is totally fine!
