### ISSUE TITLE
Documentation improvements whiteboard

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#212]
A few photos from a recent whiteboarding session with @yuvipanda - we can turn these into issues etc next week

How to structure devdocs + docstrings to make it easier to build buildpacks
![image](https://user-images.githubusercontent.com/1839645/35761899-1bb9ca6c-0843-11e8-9500-98e14d6439e7.png)

four primary uses of repo2docker

![image](https://user-images.githubusercontent.com/1839645/35761897-16749690-0843-11e8-9cf8-967aaa40219b.png)

![image](https://user-images.githubusercontent.com/1839645/35761900-21480c0a-0843-11e8-97c3-d24f637256ae.png)

**Comment by choldgraf** [comment]
cc @yuvipanda @mpacer

**Comment by willingc** [comment]
I'm all for anything that has docstrings and documentation.

4 steps:
- build
- copy
- push
- run

**Comment by choldgraf** [comment]
yes! :-)  @mpacer and I are gonna sit down this morning and try to convert those whiteboards into some actionable items too

**Comment by willingc** [comment]
I've gone ahead and tagged all open documentation issues with milestone 0.5. Let's close or do them as appropriate 👍

**Comment by choldgraf** [comment]
woot! thanks @willingc :-)

**Comment by choldgraf** [comment]
ok, gonna close this issue as it is now #214 #218 #217 #216 and #215 !  Will mark all of those as documentation and add to 0.5
