### ISSUE TITLE
Document how to cut a new release

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#215]
We should be releasing r2d more often than once every 8 months :-)

One reason this hasn't happened is that we haven't got proper documentation for how to do this (and also haven't discovered some blockers that need to be un-blocked such as giving people `pip` access). We should document the steps to release a new r2d!

**Comment by yuvipanda** [comment]
I cut a new release just now, and documented it:

https://hackmd.io/BwRhGMFYFMDMAYC0xoBYBMjXQIbGQEYBsRi64A7AMzRUAmRIdd6QA===#

**Comment by choldgraf** [comment]
everything up to step 5 is possible with a dry-run yeah?

cc @mpacer ☝️ more info on r2d structure...I'll plan to take a pass through this sometime and try to make it into a PR...if you're interested in the process too lemme know!
