### ISSUE TITLE
Write high-level architecture of the package + how to plug into this

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#217]
Describe what a buildpack is as well as how it is structured, give a pathway forward for others to create their own buildpacks (either as additions to this repo, or as other repos that could plug into r2d).

**Comment by yuvipanda** [comment]
There's a high level architecture in #235 now, but doesn't have a 'how to add buildpack' yet.

**Comment by yuvipanda** [comment]
Actually, #201 is more specifically about adding new buildpacks. @choldgraf can this be closed now that there's an architecture document?

**Comment by choldgraf** [comment]
yep, closing this now - #201 is great BTW
