### ISSUE TITLE
Running repo2docker on non-git repositories?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#234]
**A PR gets us part of the way in https://github.com/jupyter/repo2docker/pull/236 but it could use help from someone to push it over the finish line**

In this zenodo issue (https://github.com/zenodo/zenodo/issues/1416) somebody brought up the challenge that zenodo repositories are essentially zip files, they're not git repositories.

It looks like this would *not* be handled by a build-pack, since the fetching happens prior to config file detection (https://github.com/minrk/repo2docker/blob/3ab4503f7c161abc25a809bfe207234aa6471e21/repo2docker/app.py#L152). To that extent, a couple thoughts:

1. We should have documentation explaining the possibilities one way or another (e.g. a section in the docs called "does it *have* to be a git repository?") where we say either "yes" or "right now yes, but we'd love to support more workflows in the future".
2. Once we agree on 1, I can open a PR to add a docs change, and either close or convert this issue into something actionable.

**Comment by yuvipanda** [comment]
#102 and #133  are related, and have useful pointers I think.

There's two things here - one is support for this in repo2docker, and support for it in binder. Binder already has a concept of Providers, which repo2docker should also have.

Agree with documenting in the short term!

**Comment by yuvipanda** [comment]
#236 starts work on this, would be nice if someone can continue that :)

**Comment by rlconley** [comment]
I'm taking a look at continuing #236.

**Comment by betatim** [comment]
@rlconley sorry I didn't reference this issue as well, take a look at https://github.com/jupyter/repo2docker/pull/242 if you are working on this.

**Comment by nuest** [comment]
@betatim @rlconley Has there been any work on a Zenodo provider since this issue was last updated?

**Comment by betatim** [comment]
I don't know of any work on this.

The foundations are there (content providers). We'd need a new content provider that can take a Zenodo DOI and figure out the URL of the related ZIP file, download and unzip it.

**Comment by nuest** [comment]
That does not seem too hard to do :-)

I'll have to figure out first if I can run our own UI (which uses multiple microservices..) within a Binder, but I am optimistic. If so, then I'll take this on (and potentially also #102). No clear ETA, hopefully May.

**Comment by betatim** [comment]
This issue and #102 should probably be treated together.

**Comment by betatim** [comment]
Closing this as we now have Zenodo. We can create a new one for specific other sources when we think of them.
