### ISSUE TITLE
Include unzip?

### ISSUE THREAD

**Issue by kmader** [jupyter/repo2docker#251]
Unzip seems like a pretty useful tool to include in standard repo2docker images instead of manually adding it to the apt.txt, is that unreasonable?

**Comment by willingc** [comment]
Hi @kmader, Thanks for the suggestion. I know that we try to keep the base images fairly lean. I'll tag this for discussion to see if anyone on the team has thoughts on this.

**Comment by yuvipanda** [comment]
I think it's a useful and small addition. Would you like to make a PR, @kmader?
