### ISSUE TITLE
update ipykernel to work with tornado 5 so Python 2 kernels work again

### ISSUE THREAD

**Issue by fomightez** [jupyter/repo2docker#257]
Presently, the Python 2 kernels in both  https://github.com/binder-examples/python2_runtime and https://github.com/binder-examples/python2_with_3 , go dead before any code can be run.

Min RK @minrk noted:
>Min RK @minrk 13:36 @fomightez indeed, tornado was allowed to be updated to 5.0, but ipykernel is pinned to an earlier version that doesn't work with tornado 5. This needs to be fixed in repo2docker.

**Comment by AaronWatters** [comment]
Is there a work around for this?

**Comment by choldgraf** [comment]
is there a reason we couldn't just pin r2d to the latest version of ipykernel?

**Comment by minrk** [comment]
No, ipykernel should be updated to 4.8.1

**Comment by AaronWatters** [comment]
So the work around for this is to execute something like this either via `requirements.txt` or in the `postBuild` for the repository:
```bash
pip2 install --upgrade ipykernel
```
I just tested that it worked to upgrade to `ipkernel-4.8.2`.

Running `pip2` in a binder console before opening any python 2 notebooks works if don't control the repository.

**Comment by fomightez** [comment]
I can confirm Min RK @minrk suggestion on the discussion list to put `tornado==4.5.3` in the `requirements.txt` file works as a work around, too.
