### ISSUE TITLE
handle Python 2 in environment.yml

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#28]
conda can specify the Python package version in environment.yml. Right now, if the user specifies a requirement for Python 2, this will just break.

We should detect if Python 2 is in environment.yml and install to a new env for the kernel, rather than updating the root env. In fact, it might be preferable to do this if the Python version is specified as anything other than the already-installed version.

**Comment by choldgraf** [comment]
yeah I'm +1 on that - IME conda can do some weird things if you try to update python 2 -> 3 within the same environment.
