### ISSUE TITLE
Change example repo in README

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#281]
The example in the README tells people to try  `jupyter-repo2docker https://github.com/jakevdp/PythonDataScienceHandbook`. I think this repo is "broken" because of something with matplotlib(??).

It also takes a long time to build locally and I can't get it to launch reliably on mybinder.org. Can we find a different repo that builds more quickly and more reliably? I think fast runtime is important for getting started examples. We also need something that isn't totally trivial though so that people are impressed. How about https://github.com/norvig/pytudes which contains lots of interesting stuff and builds quite quickly?

**Comment by willingc** [comment]
Go for it 👍
