### ISSUE TITLE
Cannot import pwd while using jupyter-repo2docker in docker terminal

### ISSUE THREAD

**Issue by lalwanigunjan** [jupyter/repo2docker#282]
![image](https://user-images.githubusercontent.com/34087129/37725136-a1d120b6-2d08-11e8-8eb0-78ebd3c12349.png)

**Comment by willingc** [comment]
Hi @lalwanigunjan,

Windows support is still in the experimental stage [see documentation section](http://repo2docker.readthedocs.io/en/latest/install.html#note-about-windows-support). Please try another OS or the suggestion in the documenation section about WSL. Thanks.
