### ISSUE TITLE
Enable composable environments

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#293]
Right now, we say that one of the primary reasons *not* to use s2i is so that we can have _composable_ environments (e.g. python + R).

http://repo2docker.readthedocs.io/en/latest/design.html#composability

However, right now we don't actually allow for composable environments (at least with build files):

https://github.com/jupyter/repo2docker/blob/master/repo2docker/app.py#L594

In L594, we loop through build packs, and when one is detected we break the "for" loop and stop checking the other build packs. This means that if `install.R` and `requirements.txt` both exist, only the former will be built into the image.

**Comment by betatim** [comment]
Moved to #230.
