### ISSUE TITLE
Document `setup.py` build functionality

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#297]
@GladysNalvarte added the ability to build repositories from a `setup.py` file in https://github.com/jupyter/repo2docker/pull/289 , though we haven't yet put it in any of the user-facing documentation / websites. We should do this!

**Comment by betatim** [comment]
Something to point out in the docs: if your `setup.py` script needs packages installed add them to a separate `requirements.txt` which will be installed first.

**Comment by jzf2101** [comment]
Could someone give me rights and assign this to me? I can take care of this one.

**Comment by betatim** [comment]
To clarify this a bit:

> if your setup.py script needs packages installed add them to a separate requirements.txt which will be installed first.

this is to cover cases like needing to import `numpy` in your `setup.py`. In which case you should add `numpy` to your `requirements.txt`. At least that is how I now understand my somewhat cryptic comment from a month ago.

**Comment by choldgraf** [comment]
@jzf2101 done!
