### ISSUE TITLE
Build failing on repo with Julia 0.6, NoneType object has no attribute get

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#304]
via https://github.com/jupyterhub/binder/issues/73

> I am trying to build the following repo:
>
> https://mybinder.org/v2/gh/tpoisot/ScientificComputingForTheRestOfUs/master
>
> It was working up until last week-ish.
>
> When I try now, the build fails, and the only message I get is:
>
> ~~~
> Error during build: Build failing on repo with Julia 0.6, NoneType object has no attribute get
> ~~~
>
> The notebooks run on multiple machines locally.

**Comment by minrk** [comment]
That repo has an *empty* environment.yml file. I checked with `conda env create` and it doesn't seem to be technically invalid, so maybe we should support it? Should be an easy enough check:

```yaml
if not env:
    # envrionment.yml could be empty!
    env = {}
if not isinstance(env, dict):
    raise TypeError("environment.yml should contain a dictionary. Got %r" % env)
```

**Comment by choldgraf** [comment]
Interesting - this would be easy enough...it's a check on the internals of environment.yml if anything else so I'm +1
