### ISSUE TITLE
Test that images can start notebook servers

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#305]
#303 fixes a bug where the legacy buildpack can't launch a notebook server. We should probably be testing that notebook servers can start in all of our builders.

**Comment by jzf2101** [comment]
Can we close? Not sure if this is still relevant?

**Comment by minrk** [comment]
This is still relevant, since we can have buildpacks that don't work at all and the tests will pass. #343 fixes this by verifying that notebooks actually start in our test images.
