### ISSUE TITLE
 npm install not permitted

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#307]
In https://github.com/jupyterhub/binderhub/issues/558 @aborruso reports:

> Hi,
> I have `npm install -g mapshaper` in postBuild, but I'm blocked because I'm not root.
>
> Is there another way to install a nodejs package and have it ready to use after building?
>
> Thank you

Does anyone remember why we decided that `postBuild` should not run as root?

**Comment by aborruso** [comment]
@yuvipanda yes it's helpful thank you.

But without [this PR](https://github.com/jupyter/repo2docker/pull/311) it would be less comfortable.

Now `/home/jovyan/local/bin` is in the PATH and I have added this to `postBuild`

```
npm install mapshaper --prefix /home/jovyan/local/bin
cd /home/jovyan/local/bin
ln -s /home/jovyan/local/bin/node_modules/mapshaper/bin/mapshaper mapshaper
```

And I have my utilty ready to use, without using absolute path :)

**Comment by betatim** [comment]
Closing this as we now have a solution to this problem. Feel free to re-open if needed.

**Comment by choldgraf** [comment]
indeed! thanks for the quick fix @aborruso and the subsequent `.local` patch in #313  @yuvipanda !

**Comment by minrk** [comment]
If we installed npm itself with conda or nvm, then `npm install -g` would work without permission issues. I think there's also an NPM_ROOT/PREFIX env or something that should specify where `-g` installs would go. That could be pointed to a prefix that's on PATH and user-writable.

**Comment by betatim** [comment]
(reopened as Min's suggestion sounds like something we should implement)
