### ISSUE TITLE
Disable trash mechanism

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#321]
When I try to delete files via the Jupyter file browser in https://github.com/binder-examples/r built locally with d4c9c8858a4d880dedeb79ab4b4488327e9bc087 I get an error message related to the trash.

This got reported and fixed in jupyterhub/jupyterhub#1688 for JupyterHub deployments. We should implement something like this in repo2docker as well.

**Comment by GladysNalvarte** [comment]
This is not an issue anymore after Jupyter notebook and send2trash were updated. 
Closes #321
