### ISSUE TITLE
Hostname in link printed to access the notebook server

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#325]
Seems like when we switch to notebook 5.5 the link printed in the output will no longer work for people. See for example https://github.com/jupyter/docker-stacks/issues/642

Two questions:
* what is our policy for bumping versions on things like the notebook?
* should we hardcode the `--hostname` argument to docker in `repo2docker` to be `localhost` or `0.0.0.0` or something else entirely?

**Comment by choldgraf** [comment]
I'm +1 on bumping versions to latest as long as it doesn't break things. I guess in this case we should just make the `localhost` hardcoded in there. Any idea why the notebook isn't using localhost by default anymore?

**Comment by betatim** [comment]
It used to/currently print `http://0.0.0.0:62267/?token=e55a7...`. Don't know why this changed but my guess would be that for most uses cases printing the hostname of the interface is nicer for users than printing an IP address.

Instead of hard-coding things I'd check if we can turn off this behaviour via a flag.

**Comment by betatim** [comment]
I think with the default version of the notebook (v5.4) that repo2docker uses this does not happen. So my recommendation would be to stick with that instead of using the newer notebook v5.5

The way to move this forward is to help get this discussion to a point where there is consensus on how to handle this (configuration in the notebook or hardcoded command line argument or ...).

**Comment by choldgraf** [comment]
is this something that either @takluyver or @minrk have insight on?

**Comment by takluyver** [comment]
There's work underway to make the address it prints configurable: https://github.com/jupyter/notebook/pull/3668

What it printed before was right by coincidence, but with Docker it's a coincidence that comes up quite reliably, so this change has upset a few people.

**Comment by willingc** [comment]
Thanks @takluyver. 

I agree with @AaronWatters that we should strive for a solution that has minimal impact on the end user.

**Comment by AaronWatters** [comment]
Thanks @betatim -- I can confirm that the problem doesn't occur if i use
```
pip3 install --no-cache-dir notebook==5.4.1 
```

**Comment by betatim** [comment]
From https://github.com/jupyter/notebook/pull/3668 it looks like there will be a configuration option for this in notebook in the next release of the notebook.

Currently repo2docker uses notebook v5.4 so we aren't yet impacted by this. I'd suggest we don't update the default version of the notebook to v5.5 and wait till https://github.com/jupyter/notebook/pull/3668 has been merged and released. Then go straight for that version with the appropriate configuration set in the default command repo2docker executes.

**Comment by minrk** [comment]
What it printed before was right *sometimes* by coincidence - if using something like docker-machine, or mapping any port other than the internal one, e.g. `docker run --rm -it -P 8888 jupyter/base-notebook`, then it would be wrong and the container has no way of knowing what the right answer for host or port is unless it is explicitly told from outside.

**Comment by choldgraf** [comment]
I'm +1 on holding off updating the notebook until we know this issue is resolvable

**Comment by AaronWatters** [comment]
In that case I'd be in favor of some sort of a solution where the host and port is decided "from the outside" and passed in to the container somehow (env vars?) and those passed in values are printed out when the server reports the connection URL.   Sadly, I don't know the details on how to implement this, but I suspect it should be possible, maybe as some sort of a wrapper to `docker run`?
