### ISSUE TITLE
install.R not in Docs

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#326]
http://repo2docker.readthedocs.io/en/latest/usage.html#preparing-your-repository

but we have 

https://github.com/binder-examples/r

**Comment by betatim** [comment]
There is no mention of `install.R` in the section on supported config files. This would be a good issue to get started contributing to the project.

**Comment by jzf2101** [comment]
IMHO while this is a good first issue given the writeup coming with r2d I'm inclined to take this off the issues list to push the pr in time for submission

**Comment by choldgraf** [comment]
+1 to getting this in there ASAP. I think before conference season hits, we should make sure that all new features are properly documented in r2d and binder
