### ISSUE TITLE
Document using commit hashes with --ref

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#328]
Didn't see this in the docs- can we confirm the status of this capability on r2d? If so we should document it- Thanks @choldgraf for mentioning this

**Comment by betatim** [comment]
Yes this works :) I think `repo2docker --help` shows it but the online documentation doesn't.

**Comment by jzf2101** [comment]
You mean by writing `If building a git url, which ref to check out` in the help section?

**Comment by choldgraf** [comment]
So it sounds like we should change this issue to be about documenting this functionality online, yeah?

**Comment by jzf2101** [comment]
Correct.
