### ISSUE TITLE
Detailed walk-throughs in documentation 

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#332]
We've received feedback on our documentation for r2d to make it more detailed, specifically with walkthroughs.  Related: #328 #326 #297 #218 #285 #333

**Comment by jzf2101** [comment]
imho I think we need a new binder examples repo to explain this

**Comment by betatim** [comment]
I will be creating a walk through for https://github.com/Build-a-binder/build-a-binder.github.io/issues/12#issuecomment-391256075 which we can then merge here. The idea would be to have one zero2RStudio-binder and one zero2Jupyter-binder.
