### ISSUE TITLE
Allow composing multiple methods of specifying environments

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#34]
We want most people to not have to set up a Dockerfile, and be able to use other mechanisms instead. We also want most of these other mechanisms to be not things we set up and built, but rather things that already exist in the community. We want to be able to compose these together, rather than have to pick one or other.

In this vein, we should unify on one s2i builder script that can install many things. For example:

1. Install apt packages from an apt.yaml file (could include other apt repositories too)
2. Install pip packages from requirements.txt (already established convention)
3. Install conda environments with environment.yaml (already established convention)
4. Install npm packages with package.jsoin (already established convention)
5. Pick version of python used with runtime.txt (established by heroku)
6. Run a 'postInstall' script by a executable script of a particular name (TODO: find out what heroku uses)

If users don't want to put multiple files in their repo, they can instead add a `Binderfile`, which can either provide paths to these individual files that aren't the default (so you can contain them in a dir) or just contain the values of these individual files (so you can keep it all to one file).

We could use the same docker image for all of these things (not preferrable!) or produce base images that support a subset of these combinations.

**Comment by yuvipanda** [comment]
Going to edit this in a while, but we definitely *don't* want the general behavior listed here, and that's not what we ended up agreeing on. I want them to all be able to trigger (so you can have an environment.yaml file and a requirements.txt and an apt.txt file and it's all ok). I'll edit task later (I meant to edit original etherpad but never got around to it)

Most of the rest is ok :D

**Comment by choldgraf** [comment]
See the linked etherpad at the bottom...I basically just copy/pasted what was in there into this issue.

**Comment by yuvipanda** [comment]
Yeah, am pretty sure we evolved quite a bit at the end and then I forgot to update the notes. Have updated the task instead now.

**Comment by yuvipanda** [comment]
I've merged this into master now.
