### ISSUE TITLE
expose version from client

### ISSUE THREAD

**Issue by vsoch** [jupyter/repo2docker#349]
it would be great to be able to do:

```bash
jupyter-repo2docker --version
0.2.0
```
akin to:

```bash
python -c "import repo2docker; print(repo2docker.__version__)"
0.2.0
```

**Comment by betatim** [comment]
Do you want to create a PR to contribute this feature? I think it would be a welcome addition.

**Comment by vsoch** [comment]
Done! See https://github.com/jupyter/repo2docker/pull/352. And I found another fantastic easter egg! The version was called "dirty" which is pretty funny :)

**Comment by betatim** [comment]
This is because you are running from a modified git checkout. We recently switched to [versioneer](https://github.com/warner/python-versioneer/#version-identifiers) which does this :)
