### ISSUE TITLE
automated build --> deploy on circleci

### ISSUE THREAD

**Issue by vsoch** [jupyter/repo2docker#350]
Per our discussion here --> https://twitter.com/betatim/status/1018730345712226306

I can give a first shot at this! But after some sleep :)

**Comment by vsoch** [comment]
This is pretty great :)

```
# Container image Labels!
# Put these at the end, since we don't want to rebuild everything
# when these change! Did I mention I hate Dockerfile cache semantics?
```

**Comment by vsoch** [comment]
okay here is a first shot! I'll also mention a (somewhat nonrelated) bug to discuss for the repo mentioned in readthedocs!

### 1. Example Repo Bug
There is a bug with the repo provided as an example in the readthedocs, specifically this happens in the workflow:

```bash
  Downloading https://files.pythonhosted.org/packages/86/d0/b0192dc9a544da90f2d9150bcd84b981c6873e42a1f752b6affb89180ad8/scikit-image-0.12.3.tar.gz (20.7MB)
    Complete output from command python setup.py egg_info:
    To install scikit-image from source, you will need numpy.
    Install numpy with pip:
    pip install numpy
    Or use your operating system package manager. For more
    details, see http://scikit-image.org/docs/stable/install.html
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-669dg75q/scikit-image/
Removing intermediate container 25667ff23039
```

This is an error installing scikit-learn, from within the container build (so not something on the host?) I produced this on my local machine and on circleci, and I think it's an issue with this notebook dependency @jakevdp does this work for you?
https://github.com/jakevdp/PythonDataScienceHandbook

You can see the bug under the build step here:
https://circleci.com/gh/vsoch/repo2docker/6

## 2. Carry on, this one works!
I changed to the other example that I found:
 https://github.com/norvig/pytudes

and this does the trick! The container builds (no run, debug mode) if you look at the build step here:
https://circleci.com/gh/vsoch/repo2docker/10

Click on `build_deploy` to see the [tiny workflow](https://circleci.com/workflow-run/4de2419b-7797-47d0-a47e-b6d88c4b1cac):

![image](https://user-images.githubusercontent.com/814322/42750901-cafc71de-889d-11e8-8d1c-221325b130fa.png)

and then I push it to docker hub:
https://hub.docker.com/r/vanessa/repo2docker/tags/

And the configuration example is here:
https://github.com/vsoch/repo2docker/blob/add/circleci/.circleci/config.yml

Note that I removed a section I usually have to *only* deploy when coming from master branch:

```bash
          filters:
             branches:
              only: master
```

but removed it here so that you could see the example from my development branch.

## How does it work?
The user can define the following environment variables in circle:

 - `DOCKER_USER` and `DOCKER_PASS`, if found, will deploy to dockerhub
 - `CONTAINER_NAME` is the name of the container to deploy to (if not defined, will again try <username>/<reponame> I suppose some people have the same user/repo names across Docker Hub and Github!
 - `REPO_NAME`: is the full github url of the repo to build the notebook from. If not defined, will again use the repo that is being built from.

## Next steps

**documentation**

I can write up some docs for this, and of course respond to your feedback! We would want to include the "next steps" for the user to instruct others to run their jupyter container from Docker Hub. 

**pull request**

If you want to hook the repo up to circle I can wait to do a PR!

**template actions**

What other testing / metadata collection might be run on the containers / notebooks? We can do everything from registration to a server somewhere, upload of metadata, or even some kind of ping to notify people that something new is being deployed! Let's discuss. One cool thing to note is that circleci is (hopefully soonish) going to have a "template" kind of feature called an Orb --> https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/structure.md and this would mean we could have shared template recipes to do some of these things.

Lots of discuss, and I hope a PR! ...but first I really am going to go sleep for a bit first :) I was too excited to work on this!

**Comment by betatim** [comment]
> https://github.com/jakevdp/PythonDataScienceHandbook and numpy error

This is a known problem https://github.com/jakevdp/PythonDataScienceHandbook/issues/138#issuecomment-399614937

I think we should update our docs till this is fixed. pytudes seems like a good option.

**Comment by vsoch** [comment]
Affirmative! Containershare repo2docker containers have all this.

https://vsoch.github.io/containershare

Thanks all!
