### ISSUE TITLE
Error with --user-name, --image and --no-run flags

### ISSUE THREAD

**Issue by superquest** [jupyter/repo2docker#360]
I'm trying to host some Jupyter Notebooks using JupyterHub.

Step 4 of these [instructions](http://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#build-a-custom-docker-image-with-repo2docker) fails.

The command below fails, but just running `jupyter-repo2docker https://github.com/norvig/pytudes` works fine.

```
$ jupyter-repo2docker https://github.com/norvig/pytudes --user-name=jovyan --image=gcr.io/norvig/pytubes:abc123 --no-run
```

Cloning into '/tmp/repo2dockerpadg9rtq'...
remote: Counting objects: 1135, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 1135 (delta 12), reused 0 (delta 0), pack-reused 1109
Receiving objects: 100% (1135/1135), 12.36 MiB | 10.08 MiB/s, done.
Resolving deltas: 100% (625/625), done.
Using PythonBuildPack builder
Step 1/31 : FROM buildpack-deps:bionic
 ---> 7d55c5d152d2
Step 2/31 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> bc4349c7acaf
Step 3/31 : RUN apt-get update &&     apt-get install --yes --no-install-recommends locales &&     apt-get purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 237a4044643c
Step 4/31 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 143336ec36e0
Step 5/31 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> d34b60114134
Step 6/31 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> a8220dec77de
Step 7/31 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> f72421f5ed6c
Step 8/31 : ENV SHELL /bin/bash
 ---> Using cache
 ---> dc614f691202
Step 9/31 : ARG NB_USER
 ---> Using cache
 ---> da4a9600e337
Step 10/31 : ARG NB_UID
 ---> Using cache
 ---> d65b9923a958
Step 11/31 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 3d113c7a6d22
Step 12/31 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> 8eab99d3a3bb
Step 13/31 : RUN adduser --disabled-password     --gecos "Default user"     --uid ${NB_UID}     ${NB_USER}
 ---> Using cache
 ---> 1261bed3a8be
Step 14/31 : WORKDIR ${HOME}
 ---> Using cache
 ---> a1b43fa7b464
Step 15/31 : RUN apt-get update &&     apt-get install --yes --no-install-recommends        less        npm        unzip        && apt-get purge &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 6faf86ee8e30
Step 16/31 : EXPOSE 8888
 ---> Using cache
 ---> 1de5dac1cf63
Step 17/31 : ENV APP_BASE /srv
 ---> Using cache
 ---> 04946b776f84
Step 18/31 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> d8d0e02932dd
Step 19/31 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> 54f53ac0ec86
Step 20/31 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> c12e14929db3
Step 21/31 : ENV PATH ${CONDA_DIR}/bin:$HOME/.local/bin:${PATH}
 ---> Using cache
 ---> ca2763e650eb
Step 22/31 : COPY conda/install-miniconda.bash /tmp/install-miniconda.bash
 ---> Using cache
 ---> e7f398e15127
Step 23/31 : COPY conda/environment.py-3.6.frozen.yml /tmp/environment.yml
 ---> Using cache
 ---> 4f42a583b367
Step 24/31 : RUN bash /tmp/install-miniconda.bash && rm /tmp/install-miniconda.bash /tmp/environment.yml
 ---> Using cache
 ---> dfb247304c6e
Step 25/31 : USER root
 ---> Using cache
 ---> 502b5d90e9d9
Step 26/31 : COPY src/ ${HOME}
 ---> e3f74df42a5a
Step 27/31 : RUN chown -R ${NB_USER}:${NB_USER} ${HOME}
 ---> Running in c541e447b757
Removing intermediate container c541e447b757
 ---> a9f326f9c529
Step 28/31 : USER ${NB_USER}
 ---> Running in 81aba406e792
Removing intermediate container 81aba406e792
 ---> dd85dfefd5c8
Step 29/31 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> Running in d191fce028ec
Collecting numpy (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/88/29/f4c845648ed23264e986cdc5fbab5f8eace1be5e62144ef69ccc7189461d/numpy-1.15.0-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
Collecting matplotlib (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/49/b8/89dbd27f2fb171ce753bb56220d4d4f6dbc5fe32b95d8edc4415782ef07f/matplotlib-2.2.2-cp36-cp36m-manylinux1_x86_64.whl (12.6MB)
Requirement already satisfied: six>=1.10 in /srv/conda/lib/python3.6/site-packages (from matplotlib->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil>=2.1 in /srv/conda/lib/python3.6/site-packages (from matplotlib->-r requirements.txt (line 2))
Collecting pytz (from matplotlib->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/69/a7/88719d132b18300b4369fbffa741841cfd36d1e637e1990f27929945b538/kiwisolver-1.0.1-cp36-cp36m-manylinux1_x86_64.whl (949kB)
Requirement already satisfied: setuptools in /srv/conda/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->-r requirements.txt (line 2))
Installing collected packages: numpy, pytz, pyparsing, cycler, kiwisolver, matplotlib
Successfully installed cycler-0.10.0 kiwisolver-1.0.1 matplotlib-2.2.2 numpy-1.15.0 pyparsing-2.2.0 pytz-2018.5
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container d191fce028ec
 ---> afcf9932315f
Step 30/31 : USER ${NB_USER}
 ---> Running in a076259fbc57
Removing intermediate container a076259fbc57
 ---> 8252c0280e99
Step 31/31 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Running in 61e7352c23e4
Removing intermediate container 61e7352c23e4
 ---> de6631986532
{"aux": {"ID": "sha256:de6631986532933e4fb6e2fa7b7809a52c1ba730f892900061080b5ee65a74a8"}}Successfully built de6631986532
Successfully tagged r2dhttps-3a-2f-2fgithub-2ecom-2fnorvig-2fpytudes1532413478:latest
Traceback (most recent call last):
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.37/containers/7957a647e1c66bffe34ac591c13bdd445ab37b4ad7d42a76360489ef1aea60f0/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justin/.pyenv/versions/hub/bin/jupyter-repo2docker", line 11, in <module>
    load_entry_point('jupyter-repo2docker', 'console_scripts', 'jupyter-repo2docker')()
  File "/home/justin/dev/hub/repo2docker/repo2docker/__main__.py", line 7, in main
    f.start()
  File "/home/justin/dev/hub/repo2docker/repo2docker/app.py", line 672, in start
    self.run_image()
  File "/home/justin/dev/hub/repo2docker/repo2docker/app.py", line 514, in run_image
    container = self.start_container()
  File "/home/justin/dev/hub/repo2docker/repo2docker/app.py", line 560, in start_container
    environment=self.environment
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/models/containers.py", line 772, in run
    container.start()
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/models/containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/api/container.py", line 1064, in start
    self._raise_for_status(res)
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/justin/.pyenv/versions/3.6.5/envs/hub/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--user-name=jovyan\": executable file not found in $PATH": unknown")

**Comment by betatim** [comment]
Thanks for reporting this. This is a bug in the zero to JupyterHub guide. The command should be `$ jupyter-repo2docker  --user-name=jovyan --image=gcr.io/norvig/pytubes:abc123 --no-run https://github.com/norvig/pytudes`.

All the arguments have to come first, then the URL/path of the repository, and if wanted a command to run in the container once built.

Could you make a PR to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/user-environment.rst#build-a-custom-docker-image-with-repo2docker to update it?
