### ISSUE TITLE
Trouble with custom Dockerfile

### ISSUE THREAD

**Issue by superquest** [jupyter/repo2docker#362]
I run `jupyter-repo2docker  https://github.com/superquest/jupyterhub-test`

[This test repo](https://github.com/superquest/jupyterhub-test) just contains a near-empty `Test.ipynb` file and the following dockerfile which I copied from [zero-to-jupyterhub-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/singleuser-sample/Dockerfile) examples.

```
FROM jupyter/base-notebook:c7d997f2db86
# Built from... https://hub.docker.com/r/jupyter/base-notebook/
#               https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile
# Built from... Ubuntu 16.04

# conda/pip/apt install additional packages here, if desired.

# pin jupyterhub to match the Hub version
# set via --build-arg in Makefile
ARG JUPYTERHUB_VERSION=0.9.*
RUN pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION
```

And the result is a Jupyter environment with no `Test.ipynb` file and a mysterious, 4 month old, empty `work` directory!

![blank](https://user-images.githubusercontent.com/4335621/43178001-d0769c76-8f90-11e8-90b5-13d11fe6f18c.png)

**Comment by superquest** [comment]
Now that I think about it, I guess that the config.yaml file wouldn't matter because that's a helm thing ...

**Comment by choldgraf** [comment]
The "work" thing is indeed mysterious haha. However, it's not enough to just copy/paste from the zero to jupyterhub guide. repo2docker needs a few particular lines in the Dockerfile (we're treating Dockerfiles as advanced usecases). I recommend checking out the [documentation for Dockerfiles in Binder](https://mybinder.readthedocs.io/en/latest/dockerfile.html) (which will also work for repo2docker)

**Comment by vsoch** [comment]
I believe that "work" is the default WORKDIR from the Julia base container? 

 - created here --> https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L56
 - set [here](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L105) because in $NB_USER home. 

I think you would be better off first trying just getting rid of the Dockerfile (and then the repo2docker will handle generation) or to read the docs linked from @choldgraf to understand how things are working.

**Comment by superquest** [comment]
> I think you would be better off first trying just getting rid of the Dockerfile

That's what I ended up doing.

Thanks @choldgraf for the documentation link.

**Comment by betatim** [comment]
Closing this as it seems like the issue has been resolved. Feel free to reopen.
