### ISSUE TITLE
repo2docker for julia+jupyter?

### ISSUE THREAD

**Issue by vsoch** [jupyter/repo2docker#365]
Is there a solution yet for a julia notebook via repo2docker? I'm pretty new to Julia, but I put together my first Jupyter+Julia container (not using repo2docker, but using the continuous-builder) and it would probably be similar/trivial to have the same sort of execution for a julia notebook, just with some list of julia requirements and copying files to the place where julia expects them.

**Comment by vsoch** [comment]
I'm still futzing around like a lost penguin (I need to do testing to figure out how to best run the container and pull to Singularity) but if it's helpful, here is what I was working on so far - this is generated from a repo with a modified circleci to also push metadata back to Github pages, and just build a standard Dockerfile, with the anchor bits to reference different "functions" in the config.

 - https://vsoch.github.io/julia-share/
 - https://hub.docker.com/r/vanessa/julia-share/
 - https://circleci.com/workflow-run/dfa766a9-821a-4214-b5d6-74715d97e17e

I'm going to have a writeup for the containershare (it's a nice little registry that anyone can pretty easily deploy to get the resulting table and linked containers) but for now I hope the links above can suffice. 

I have no idea how jupyter can handle ipython **and** R **and** julia! It's like, magic. :sparkles:

**Comment by betatim** [comment]
To install Julia dependencies check out http://repo2docker.readthedocs.io/en/latest/config_files.html#require Is this what you were looking for?

**Comment by vsoch** [comment]
Yes! This one --> https://github.com/binder-examples/julia-python is exactly what I would want! Thank you :)
