### ISSUE TITLE
[question] Who is joyvan?

### ISSUE THREAD

**Issue by vsoch** [jupyter/repo2docker#366]
Just curious - I keep seeing him / her / it everywhere!

**Comment by ryanlovett** [comment]
Jovyan : Jupyter :: Jovian :Jupiter

https://en.m.wikipedia.org/wiki/Jovian

**Comment by vsoch** [comment]
ohhhhh! Thank you! I love it <3

**Comment by darighost** [comment]
This thread sparks joy
