### ISSUE TITLE
broken link and postBuild is not executable 

### ISSUE THREAD

**Issue by consideRatio** [jupyter/repo2docker#367]
I was going to test repo2docker on my repo https://github.com/consideRatio/jupyter-se-math-teacher, but it failed because postBuild was not set to be executable.

```
ValueError: binder/postBuild is not executable, see http://repo2docker.readthedocs.io/en/latest/samples.html#system-post-build-scripts for help.
```

1. This is a broken link
2. Can't repo2docker just go `chmod +x <the-file>` first?

**Comment by betatim** [comment]
r2d marks `postBuild` as executable automatically: https://github.com/jupyter/repo2docker/blob/465177c0cb170915bfd38ecaadb1720c304f7d23/repo2docker/buildpacks/base.py#L129 maybe this change isn't in the released version yet?

The link should probably be http://repo2docker.readthedocs.io/en/latest/config_files.html#postbuild

**Comment by consideRatio** [comment]
Ah thanks @betatim ! This is a duplicate of #240 and I've verified that the master does alright but a new version must be released first - I did not find the outdated link anywhere in the master either.
