### ISSUE TITLE
Easy way to run a single repo on your own cloud instance

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#37]
We want to provide really easy ways for users to run a github repo on their own AWS or gcloud or OpenStack whatever instance. It should ideally allow them to do persistent long term work on it, including pushing stuff back to GitHub. We can use cloud-init + packer to make this happen across clouds without too much work on our part.

We also have a responsibility to do this as securely as possible, rather than leaving random botnet invitations across the internet.

**Comment by yuvipanda** [comment]
Note that this will be only for single-users - we should also have this for binderhub itself (which is multiuser).

**Comment by jzf2101** [comment]
@yuvipanda following up on this I'm trying to build images on GCP but I don't know how to get access to the juptyer noteobok port after I get everything to build?

**Comment by yuvipanda** [comment]
@jzf2101 can you tell me the repo2docker commandline you used?

Some things off the top of my head:

1. When creating the VM, make sure 'allow HTTP access' is ticked
2. In the URL repo2docker gives you when running, replace the IP it has with the public IP of your VM

Can you also post the IP you get from repo2docker? It *might* only be listening on localhost, in which case we've to figure out how to expose it to the world securely.

**Comment by jzf2101** [comment]
I only got local host

**Comment by betatim** [comment]
With that setup something like from your local machine: `ssh -L47821:127.0.0.1:47821 <remote-machine>` should work. Then open `http://127.0.0.1:47821/?token=88301f2909764d7c9a65e8ec7c541398f03b001d6557ce8b` on your local machine.

**Comment by jzf2101** [comment]
@betatim can you explain more what you mean by ssh -L47821:127.0.0.1:47821 <remote-machine> ?

**Comment by betatim** [comment]
The notebook server will only be listening on localhost so one way to connect from your computer is to create a tunnel from your computer to the remote machine which you are running repo2docker.

This looks like a good article to learn a bit more about port forwarding with ssh: https://www.ssh.com/ssh/tunneling/example

**Comment by jzf2101** [comment]
I read somewhere that people running jupyter notebooks specify a port in their config and then call `jupyter-notebook --no-browser --port=<PORT-NUMBER>` but there's no way to pass that information into the jupyter notebook server in the Docker image correct?

**Comment by betatim** [comment]
You can set the command `repo2docker` runs in the container and thereby replace the default command (which runs Jupyter notebook).

Something like `repo2docker /path/to/repo jupyter-notebook --no-browser --port=1234 --more-args --here`. You need to experiment with what command exactly it is you want. Check https://github.com/jupyter/repo2docker/blob/fdcfb816890fb9d896e4254be7e20ef72f8d625e/repo2docker/app.py#L595-L603 to see the default command.
