### ISSUE TITLE
Node 6+ is Required

### ISSUE THREAD

**Issue by blink1073** [jupyter/repo2docker#387]
Hi!  We found [here](https://github.com/jupyter/repo2docker/issues/374#issuecomment-416179048}) that Node 6+ is required to install JupyterLab extensions.  It can be installed from conda as `nodejs`.

**Comment by betatim** [comment]
The intent of https://github.com/jupyter/repo2docker/blob/dce30421accfc83edd876185b248a148be8c13aa/repo2docker/buildpacks/base.py#L46-L49 (combined with a few lines later having nodejs in the list of base packages) is to have node 10 installed.

Could you check with `master` if it does?

**Comment by blink1073** [comment]
Thanks, @betatim!.  @vsoch, I looked at your fork and it is using a version of that file before the update.

**Comment by vsoch** [comment]
Interesting, so what version would we want to install here? (currently is 0.5.0)

https://github.com/vsoch/repo2docker-jupyterlab/blob/master/.circleci/config.yml#L139

**Comment by blink1073** [comment]
It looks like 0.6 is not quite finalized: https://github.com/jupyter/repo2docker/releases

**Comment by vsoch** [comment]
ah ok, I'll just be on the lookout then! Thanks @blink1073

**Comment by blink1073** [comment]
Yep!
