### ISSUE TITLE
git-credential-env not working in debian

### ISSUE THREAD

**Issue by zymergen-luke** [jupyter/repo2docker#388]
The dockerfile for repo2docker is based on Debian (as well as the builder image used by binder). Debian replaces `/bin/sh` with `dash` - a shell with a version of the echo builtin that does _not_ support the `-e` flag. When using git-credential-env in this environment, it will produce
```
-e username=foo
password=bar
```
rather than the correct
```
username=foo
password=bar
```
that git expects. This prevents git-credential-env from working when inside the container.

The current contents of git-credential-env are:
```
#!/bin/sh
echo -e $GIT_CREDENTIAL_ENV
```

There are a couple possible workarounds:
1. Use `/bin/bash` instead of `/bin/sh` (adds a dependency on bash)
2. Modify the dockerfile to provide the proper flavor of `sh` (Not likely to work when switching image bases)
3. use `/bin/echo` rather than the `echo` builtin of the shell (though this introduces the opposite problem - e.g. /bin/echo on a mac does _not_ support -e while /bin/echo on debian _does_)
4. simply drop the `-e` (similarly, this will only work on half the systems).

Given that `/bin/echo` is non-uniform and even `/bin/sh` is non uniform, I would suggest we go with option 1 - always specify `/bin/bash` explicitly. This slightly raises the bar for dependencies, but I think bash is ubiquitous enough that it is a worthwhile tradeoff.

**Comment by yuvipanda** [comment]
Fixed with #389
