### ISSUE TITLE
use `os.path.join` for source paths

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#39]
I noticed that a few paths are written with 'nix-style separators. We should remove all instances of these and us `os.path.join`. This mostly pertains to Yuvi's dockerfiles branch

**Comment by yuvipanda** [comment]
This turned out to be harder than it looks - *inside* the Dockerfile, you always want to use Linux paths, but outside you want to use os.path.join.

**Comment by yuvipanda** [comment]
This has been fixed!
