### ISSUE TITLE
Update default Julia version and/or allow customization

### ISSUE THREAD

**Issue by NHDaly** [jupyter/repo2docker#392]
Hi! Currently, repo2docker chooses `julia v0.6.0` by default, but there are several newer versions of julia that would be better choices.

The default is set here:
https://github.com/jupyter/repo2docker/blob/7552361c2b51bea73f3c2fba5e290d6b834b7f36/repo2docker/buildpacks/julia.py#L38

Better default values would be any of:
- v0.6.4 (the last 0.6 release)
- v0.7.0 (the "compatibility" release, which is mostly compatible with code written for 0.6 and code written for 1.0)
- v1.0 (the latest stable release. However lots of code and packages still aren't 1.0 ready yet.)

I personally think setting `v0.7.0` as the default makes the most sense.

-----------------------

As a separate thing, it would be nice if we allowed the user to choose a julia version in the REQUIRE file, as is commonly done in julia REQUIRE files:
https://github.com/JuliaLang/IJulia.jl/blob/master/REQUIRE#L1
https://github.com/JuliaPlots/StatPlots.jl/blob/master/REQUIRE#L1

This way, the user can choose between julia 0.6, 0.7, and 1.0.

If you think these should be two separate Issues, let me know and I'll split them up! :)

**Comment by davidanthoff** [comment]
Maybe 1.0 would be the best default at this point? But I almost would prefer that one _must_ specify a julia version somehow. Whatever default we pick will be outdated soon, but updating a default here will break a lot of stuff everytime we do. So not support a default in the first place might be a good idea...

**Comment by davidanthoff** [comment]
Alright, scrap that :)

I think the right approach is this:

if there is a `Project.toml` (or `JuliaProject.toml`, then generally ignore any `REQUIRE` file. If there is no julia version info inside `Project.toml`, then use the latest released version of julia. If there is julia version info inside `Project.toml`, then use the highest version that is compatible with the constraint that is in the `Project.toml`. 

If there is _no_ `Project.toml` or `JuliaProject.toml`, _and_ there is no julia version info inside `REQUIRE`, use the highest julia 0.6.x version.

**Comment by betatim** [comment]
Sounds like a good plan.

For Python we do have a default version and bump it occasionally. The assumption is that those who don't specify a version don't care beyond "it is Python 3". I think people would be surprised if the default Python was 2.7 hence 3 is the default.

There was some discussion around when to make Julia 1.0 the default over 0.6.x in one of the PRs that added support for 1.0. My guiding principle would be "do what is least surprising to a typical Julia user".

**Comment by betatim** [comment]
[FAQ entry on versions](https://repo2docker.readthedocs.io/en/latest/faq.html#what-versions-of-python-or-r-or-julia-are-supported) and [source: docs/source/faq/rst](https://github.com/jupyter/repo2docker/blob/master/docs/source/faq.rst).

**Comment by NHDaly** [comment]
> Alright, scrap that :)
> 
> I think the right approach is this:
> 
> if there is a `Project.toml` (or `JuliaProject.toml`, then generally ignore any `REQUIRE` file. If there is no julia version info inside `Project.toml`, then use the latest released version of julia. If there is julia version info inside `Project.toml`, then use the highest version that is compatible with the constraint that is in the `Project.toml`.
> 
> If there is _no_ `Project.toml` or `JuliaProject.toml`, _and_ there is no julia version info inside `REQUIRE`, use the highest julia 0.6.x version.

Yes, I completely agree! This is what Kristoffer and I came up with as well (here: https://github.com/jupyter/repo2docker/pull/393#issuecomment-419558127)

**Comment by davidanthoff** [comment]
I believe we sorted this one out as well and can close?
