### ISSUE TITLE
Support DESCRIPTION files for R projects

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#396]
https://github.com/benmarwick/rrtools/blob/master/DESCRIPTION

These have been mentioned a few times to me as a way that R users specify dependencies. We should try and find out how popular they are and consider supporting htem in addition to `install.R`.

**Comment by betatim** [comment]
After your investigations: should we still attempt to add support for `DESCRIPTION` files? They could be used in the same way as `setup.py` is currently supported (if there is nothing else but a `setup.py` we assume this is a repository for a package and the user wants us to run `pip install -e.`. This makes it super nice for trying out "random" packages.

**Comment by gedankenstuecke** [comment]
Yep, I think the `DESCRIPTION` support would be valuable and should be pretty easy as you can run the equivalent of `pip install -e.` for `R` to do the install of the package! For `packrat` I've given up for now as it seems to be not mature enough (or I'm too unskilled in R!)
