### ISSUE TITLE
Adding Personal Package Archives (PPAs)

### ISSUE THREAD

**Issue by mizvol** [jupyter/repo2docker#402]
Currently, it is impossible to add PPAs through `postBuild` and `apt.txt`.
The reason is that `apt.txt` is executed before `postBuild`, so even if a PPA is added to the `postBuild`, the package cannot be found.

In some cases, there is a need for software that is distributed through PPAs. For example, if one needs to install MongoDB, it is required to add a PPA and create a list file. Only then, the package is becoming available for installation.

**Comment by mizvol** [comment]
Thanks, @betatim. Your solution worked for me.
I've managed to install mongodb by adding the following line to ```postBuild```:
```conda install -c anaconda mongodb```

Although, there is another issue. To use mongodb, I need to start a service ```service mongod start```. I tried starting the service from MyBinder terminal and by adding the command to ```postBuild```. In both cases I get an error ```mongod: unrecognized service```. 

**Is it possible to start a service in MyBinder?**

**Comment by betatim** [comment]
We support `environment.yml` (check out https://github.com/binder-examples/conda) so I would list mongodb there instead of using `postBuild`.

To start a service like a DB we support a special file called `start`, see https://repo2docker.readthedocs.io/en/latest/config_files.html#start. We discovered that this was broken, got fixed in #399 which should be deployed on Tuesday. You could already test it locally with repo2docker installed from master.

**Comment by mizvol** [comment]
Indeed, `start` script works now (tested locally). Nonetheless, the error `mongod: unrecognized service` still pops up in the logs.

No problem with MyBinder here though. Seems like conda-forge MongoDB package does not contain MongoDB server. So, as you proposed before, the only way to install MongoDB is to create a custom `Dockerfile` and install MongoDB properly.

**Comment by yuvipanda** [comment]
IMO, PPA support should exist in an extension or with a Dockerfile.

@mizvol for running extra services, https://blog.ouseful.info/2019/02/04/running-a-postgresql-server-in-a-mybinder-container/ from @psychemedia might be useful.

**Comment by psychemedia** [comment]
I need to get mongo up and running in Binder too... will have a look at this when I get back from hols if s/one doesn't post a recipe before me.

**Comment by betatim** [comment]
I agree with Yuvi that PPAs should be for people who have custom `Dockerfile`s.

Closing this, if someone wants to come back to this specific issue feel free to re-open it.
