### ISSUE TITLE
Julia tests keep erroring

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#403]
Travis keeps timing out while running the Julia tests. I don't think this is a real failure and instead something is too slow in our test that leads to no output being produced for 10minutes and then the job gets stopped by travis.

First step is to investigate why our Julia test takes so long to run without producing any output. Ideally we could speed the test up so it runs much more quickly. If we can't do that then use `travis_wait` for the julia tests (as we do for the R tests).

**Comment by davidanthoff** [comment]
I think this can also be closed?
