### ISSUE TITLE
What versions of python are supported by r2d?

### ISSUE THREAD

**Issue by allisons** [jupyter/repo2docker#408]
I attempted to make an image with python3.7 and failed.  I was able to read between the lines to determine that 3.6 is as far as g2d supports and fixed it on my end, but maybe the FAQ could explicitly call that out?

**Comment by betatim** [comment]
Thanks for making this note.

#405 will add support for 3.7 so when we write the FAQ we should keep an eye on it so we don't create an out of date answer.

Did you use an `environment.yml` to setup your repository?

**Comment by minrk** [comment]
I added some text to the faq in #405. Hopefully that makes it clearer

**Comment by jzf2101** [comment]
We mention what we support in https://repo2docker.readthedocs.io/en/latest/config_files.html#id2 as well
