### ISSUE TITLE
RStudio Initialization Errors/ Unable to Connect to Service 

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#417]
I've been getting these bugs lately, does anyone know how we would suggest debugging a build ?

**Comment by ryanlovett** [comment]
nbrsessionproxy launches `rserver --www-port=some_unused_port` then proxies that web service on /rstudio. If you want to debug you could try picking some unused port, drop to a jupyter terminal, and run `rserver --www-port=your_port`. If rserver starts correctly, open a new tab on your notebook server with proxy/your_port/ appended, e.g. https://hub.mybinder.org/user/somebinderuser/proxy/your_port/.

One binder-specific debug trick I use is to run `cat /proc/1/fd/2` in a jupyter terminal so I can see notebook's stderr.

**Comment by yuvipanda** [comment]
nbrsessionproxy has been rewritten (and renamed to jupyter-rserver-proxy) several times, so I'm going to close this one for now. Please re-open if you run into this again!
