### ISSUE TITLE
Make a logo for repo2docker?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#423]
Sometimes I'd like to have a visual way to describe repo2docker. Right now, It's hard to do this because there's no "visual" component to this project. Are folks generally +1 on having a logo of some kind for this project?

**Comment by jzf2101** [comment]
@tgeorgeux do you have any thoughts on what we should do?

**Comment by tgeorgeux** [comment]
I would probably go with some combination of https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png, the number 2 and the whale logo. Seems like a good place to start at least :)

**Comment by jzf2101** [comment]
is there an IP issue wiht that?

**Comment by tgeorgeux** [comment]
This is where I would check for that. https://git-scm.com/about/trademark

**Comment by betatim** [comment]
Can we use maybe a folder icon instead of a git logo so that we don't need to change the logo when we support things other than git repositories as source of the "repo"?

Some other ideas:
* a picture of a shipping container which on the left is shown as a sketch/drawing, the middle half of the container is half built and the right half is fully assembled. Kinda of showing how we go from a drawing of a repo to a fully made container
* a cartoon style production line that spits out shipping containers

Thoughts:
* don't get too tied to git
* ideally even get away from "docker" and instead focus on "container"
* has to print well to stickers
* red is a cool colour
* convey the idea that repo2docker constructs, builds or assembles stuff by following a recipe/blueprint
* the recipe is easy to follow like Ikea instructions
* repo2docker is a craftsman, proud and opinionated about what it builds
* repo2docker is simple and its logo is too

**Comment by agahkarakuzu** [comment]
If I were to stick with the marine deck equipment theme, would repo2docker be the crane that puts containers on the back of the whale, or would it rather be the operator of the crane, following instructions written on a paper?

**Comment by agahkarakuzu** [comment]
This illustration is from [Behance](www.behance.net). Maybe works as an inspiration trigger and can be used in a presentation (CC, non-comercial, no-derivatives) by giving credit to the source. I will try to come up with something more closer to @betatim's points. 

![image](https://user-images.githubusercontent.com/9632322/46902646-b7de1000-ce96-11e8-9e25-594c64e4d2ec.png)

**Comment by betatim** [comment]
I like the idea of a crane operator following instructions. One thing that might give the wrong impression: cranes shift around many containers but repo2docker just deals with one at a time. Maybe it is my kubernetes brain that is thinking: many containers, aha, must be a tool for orchestration!

**Comment by agahkarakuzu** [comment]
@betatim I agree! So I combined and stylized some free vector graphics from [freepik](www.freepik.com) and created this mockup:

![repo2docker](https://user-images.githubusercontent.com/9632322/46903733-0398b580-cea7-11e8-9dc8-e2c9eac69e69.png)

**Comment by betatim** [comment]
This looks cool!

What do you think of a left to right container from drawing to finished with a person somehow interacting with it?

Should we already start thinking about how it will look when it is the size of a GitHub avatar logo or too early for those kinds of constraints?

**Comment by choldgraf** [comment]
first off, these are super cool graphics, thanks @agahkarakuzu :-)

I think this is a nice start, with a few caveats. For me, designing a logo needs to happen with at least these constraints:

* Looks good from far away, and from up close
* Can be displayed with at most 3 colors

What if we took @agahkarakuzu 's design above, and made it more about dropping a repo *into* a container (or, finding another abstract way to symbolize "creating" a container, but that doesn't depend on color gradients because that breaks my 2nd rule of logo design :-) )

**Comment by agahkarakuzu** [comment]
@choldgraf not at all! The design was just to flesh out some ideas. I think we need such intermediary steps as the concept is quite abstract. Totally agree that a sane logo design should not go beyond tricolor and should be "iconazible" :) A question, would you prefer sticking with the colors in the Binder's logo? 

You can also sketch your design ideas, I can create svg drawings from them. 

> What do you think of a left to right container from drawing to finished with a person somehow interacting with it?

@betatim I think having such designs is always a good idea, would come in handy for presentations. I am quite used to creating them without much effort, so do not hesitate :)

**Comment by agahkarakuzu** [comment]
@choldgraf noted. I will keep thinking and try to come up with something, is there a deadline for this? Please share if you have any ideas to symbolize "software environment".

**Comment by betatim** [comment]
> I am quite used to creating them without much effort, so do not hesitate :)

This is why open-source is awesome. I could at best create a stick man drawing with a pencil and then take a picture of it :)

Let's collect some more ideas and sketches before we put on the straight jacket of "serious logo design".

What is a good pictogram to represent a "repository"? A folder like 🗂? A [filing cabinet](https://www.officeworks.com.au/shop/officeworks/p/soho-2-drawer-filing-cabinet-white-jbsoho2dwe)? It is something you store stuff in.

> is there a deadline for this? 

Not really. We should try and not let it drag on forever but also not be in a hurry. Especially as people are giving their free time.

**Comment by betatim** [comment]
Another idea via twitter https://twitter.com/blairhudson/status/1051377648578916352

**Comment by agahkarakuzu** [comment]
I think this is a good design to work with! Putting empty sheets inside the container from sideways may be a better idea to represent the repo2docker's function (vs gravity). Branch out icon can be placed on the first sheet,  as the container is for docker. 

I mean something like this:

![rep2dec](https://user-images.githubusercontent.com/9632322/46919547-b56ed980-cfae-11e8-9a73-38352115ba23.png)


I think there is still a missing component. Repo and docker are there, but we are missing "2", like an arrow pushing them inside the container etc.

**Comment by choldgraf** [comment]
nice @agahkarakuzu! I like where this is heading - maybe per @jzf2101 's comment we can simplify a little bit and make the angle a bit less-pronounced so it's more readable. I think that'd look nice!

**Comment by agahkarakuzu** [comment]
Alright, I see your points. With this particular perspective, I cannot change the angle of the icon, otherwise it will look like intersecting with the paper instead of laying on its surface. 

If everybody agrees on a shipping-container-like cube, a stack of papers and the branch out icon as the components of the logo, happy to iterate till everyone is happy. 

@blairhudson, do you have .eps or .ai (or any other format that includes layers) for your design?

**Comment by jzf2101** [comment]
Yes, I agree. I guess my suggestion was to possibly change the particular perspective

**Comment by betatim** [comment]
Would it help with the angle if we make the sheets horizontal instead of vertical?

Or maybe we have them vertical but rotate them 90degrees around the axis that is from the ground upwards towards the sky. A bit like when you look at a bookshelf with some books pulled out. So the pages/sheets are being pulled out of the container. Maybe a bit like [this](https://www.alamy.com/stock-photo-hand-pulling-a-book-from-a-library-shelf-62190371.html)

**Comment by jzf2101** [comment]
I don't quite understand what you mean but maybe someone else does

**Comment by betatim** [comment]
> horizontal instead of vertical

Right now the sheets are standing up (vertical). For horizontal: imagine a stack of paper, that is what I imagine.

> rotate the sheets

right now the sheets are like a sliding door on the container. I was thinking of orientating them like when you put books into a shelf. So they go into the container a bit.

**Comment by blairhudson** [comment]
> @blairhudson, do you have .eps or .ai (or any other format that includes layers) for your design?

@agahkarakuzu the attached zip contains the original .sketch file, and .eps and .png exports.

[repo2docker.zip](https://github.com/jupyter/repo2docker/files/2476833/repo2docker.zip)

**Comment by agahkarakuzu** [comment]
Thank you @blairhudson! @betatim I understood what you meant. I will try reflecting those into a new design when I can find some more time.

**Comment by blairhudson** [comment]
@betatim @agahkarakuzu how about something like this?

![repo2docker_v2](https://user-images.githubusercontent.com/271893/46944629-441e4c00-d0be-11e8-87f8-a1212f6b5ccc.png)

.sketch/.eps/.png bundle: [repo2docker_v2.zip](https://github.com/jupyter/repo2docker/files/2478305/repo2docker_v2.zip)

**Comment by agahkarakuzu** [comment]
@blairhudson, I guess this adresses @betatim's points. This perspective uses less shading, which is also a plus! As we are used to following processes and reading text left to right, repo2docker is better captured in that sense too. Still thinking of what would be a good idea for "2".

**Comment by blairhudson** [comment]
> Still thinking of what would be a good idea for "2".

@agahkarakuzu some thoughts:

- the repo files gradually stacking "in to" a container, possibly needs some sort of arrow to make this more evident
- the side panel could have 2 bars instead of 3
- 2 files instead of 5

**Comment by choldgraf** [comment]
@blairhudson I quite like this one (https://github.com/jupyter/repo2docker/issues/423#issuecomment-429786626)! FWIW, I don't think that we need to visually capture every possible thing that repo2docker does, or else this logo is going to become really really busy :-)

**Comment by jzf2101** [comment]
i agree @blairhudson I think it's more visually clear.  We can iterate on this, but generally I'm happy with this direction

**Comment by betatim** [comment]
It seems like https://github.com/jupyter/repo2docker/issues/423#issuecomment-429786626 is popular. Can we define what would be needed before we adopt it as the v1 of the  logo for repo2docker?

We should make a short list and work through it. From my point of view having the general theme and idea sorted out is what is needed. Once we start using it we can iterate on it as we do with everything else.

**Comment by choldgraf** [comment]
hey all - I'm gonna close this because #455 is now open and we can take discussions there. If nobody chimes in by the 5th of November, then we'll merge that logo in as "the" logo for now (updates are welcome in the future though!)

So, I guess what I'm saying is, remember remember the 5th of november.

Thanks again for everybody's thoughtful contributions and ideas!!! :-)

**Comment by betatim** [comment]
@blairhudson could you export the sketch file to a SVG as well?

It would be great to have a "source" file that can be opened without buying a sketch license.

**Comment by agahkarakuzu** [comment]
Hey all,  I was (and still am) under tight deadline for abstract submission, sorry I could not be responsive. This is a beautiful design and happy to help out with whatever it may need after 7th :)

**Comment by blairhudson** [comment]
> @blairhudson could you export the sketch file to a SVG as well?

Here's a new zip that also includes the SVG: [repo2docker_v2.zip](https://github.com/jupyter/repo2docker/files/2548509/repo2docker_v2.zip)

**Comment by choldgraf** [comment]
wooo, the logo is now merged!

big thanks to @agahkarakuzu and @blairhudson for all of your help in the design!
