### ISSUE TITLE
JupyterLab 0.35.1 is available

### ISSUE THREAD

**Issue by blink1073** [jupyter/repo2docker#438]
This is available for use in repo2docker, if you're ready to upgrade.

**Comment by choldgraf** [comment]
+1 (if anybody has a moment to do this, [here are the instructions for bumping default versions](https://github.com/jupyter/repo2docker/blob/master/CONTRIBUTING.md#update-and-freeze-buildpack-dependencies))

**Comment by jzf2101** [comment]
Don't we need to cut a release as well to put it on pip?

**Comment by jzf2101** [comment]
How would we deal with freezing the bumping the conda environment when jlab requires python 3.6 and not other versions?

**Comment by yuvipanda** [comment]
Closing in favor of #724, since we already have 0.35 installed.
