### ISSUE TITLE
Docs page has lost its sidebar

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#449]
https://repo2docker.readthedocs.io/en/latest/ now doesn't show a menu/sidebar anymore and seems to miss the title below the logo.

<img width="843" alt="screen shot 2018-10-19 at 18 01 12" src="https://user-images.githubusercontent.com/1448859/47229855-0b85b780-d3c9-11e8-8ff8-ece8a1b3a872.png">

cc @choldgraf the sphinx templates level 11 wizard 🧙‍♂️

**Comment by choldgraf** [comment]
noooo ok will try to debug this
