### ISSUE TITLE
Add "caching" functionality similar to BinderHub's

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#452]
In #450 we discussed the possibility of creating a container from an existing image that repo2docker built previously. Currently when you run repo2docker again it has to re-execute the steps after copying the source repo over. This can take a long time if you have a lot of dependencies or R packages.

For git repositories we could add a functionality similar to BinderHub's that checks the local registry for previously built images and reuses them. This would make it a lot faster to launch and re-launch repositories that haven't changed.

**Comment by choldgraf** [comment]
this is an interesting idea - and sort of opens a door to having "fancier base images" that users can choose and then build off of...

**Comment by betatim** [comment]
> fancy base images

My understanding of this idea is that it should provide the answer to: "I am a computational train spotter, how do I quickly get all the software that the comp train spotter community is using setup and running for my analysis?". I think the answer would be to have a repository "comp-train-spot" (maintained by someone, not exclusively r2d) that functions like a cookie cutter that has all the repo2docker config setup. I copy that repo, call it "swiss-trains-winter-18" and then do my work.

Hopefully over time the number of such "base repos" grows to areas beyond computational train spotting. Is this what you had in mind too or did you think of base images in the docker image sense to use in a `FROM` statement? Should we make a new issue to get to a common understanding and then  hash it out?

When I posted this I was thinking of the following problem:

* run `repo2docker https://github.com/binder-examples/requirements`
* change nothing in the remote repo
* then run `repo2docker https://github.com/binder-examples/requirements` again and it will rebuild the container instead of launching the existing image.

Changing this so that the first run builds the image and the second reuses it is what I had in mind.

For local repositories this works already unless you edit some code that isn't related to the environment. For this #410 is relevant.

**Comment by choldgraf** [comment]
yeah I think from a technical perspective that's what I had in mind too. From a "future feature" perspective I was thinking stuff like "I want the Neurodebian neuroscience Docker image with this one extra package and some data downloaded" and the build process would be way faster because the Neurodebian image is cached

**Comment by betatim** [comment]
Closing as #511 got merged as the more successful cousin of #461
