### ISSUE TITLE
Proposing a logo for repo2docker

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#455]
repo2docker doesn't have a logo which means its documentation page looks somewhat blank and makes it tricky to represent on slides. Also, what serious project doesn't have a logo :) Here is a proposal arrived at in #423:

![46944629-441e4c00-d0be-11e8-87f8-a1212f6b5ccc](https://user-images.githubusercontent.com/1448859/47529400-ff599880-d8a7-11e8-845c-10d5d55d2037.png)

To move this forward at a steady but consistent pace the idea is to agree the basic ideas of the logo (individual pages with a fork symbol on them (representing the repo) and a container) and then:

* Colour scheme (e.g. do we want to adopt any of the Jupyter colors?)
* Structure and layout

Like the code and documentation this logo doesn't have to be perfect on day one and the expectation is that we'd keep tweaking it for a while.

What do you think of this? If you'd like to change something can you try and make a specific suggestion for what to change and how. This would help us in actually making it happen. You can check #423 for how things evolved, other ideas and inspirations that lead to where we are now.

This issue will stay open for at least 5 November 2018. Unless there are strong objections by that time this would become "the logo".

here's a link to the raw logo files: https://github.com/jupyter/repo2docker/files/2548509/repo2docker_v2.zip

**Comment by choldgraf** [comment]
A ping on this issue! @betatim perhaps we should turn this into a PR that gets merged on the 5th unless there is objection from somebody?
