### ISSUE TITLE
Next steps for repo2docker

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#462]
This issue collects "next steps" for the project. Each step should fit into one of the following three categories:
* **now**, very concrete/actionable step that is ready for someone to pick it up and work on
* **soon**, less concrete/actionable step that is going to happen soon, discussions around the topic are coming close to an end at which point it can move into the "now" category
* **later**, abstract ideas or tasks, need a lot of discussion or experimentation to shape the idea so that it can be discussed. Should also contain concrete/actionable steps that have been postponed on purpose (these are steps that could be in "now" but the decision was taken to work on them later)

Please leave comments on the order/ideas mentioned here and I will incorporate them. The plan is to start with this list and as things get done or removed add new ones. This means this list should not be exhaustive, it should only represent the "top of the stack" of ideas.

Let's see if we can keep this as an issue instead of a file to make it easier to update. my suggestion would be to use this issue to create a first list and a short "user manual" for it, then create a new issue titled "ROADMAP" and use that from then on with the top comment in that issue representing the ROADMAP at all times.

Guiding thought for the next months:
Repo2docker is a dependable tool used by humans that reduces the complexity of creating the environment in which a piece of software can be executed.

## Now
* reduce documentation typos and syntax errors
* Julia Manifest support (https://docs.julialang.org/en/v1/stdlib/Pkg/index.html)
* increase test coverage (https://codecov.io/gh/jupyter/repo2docker/tree/master/repo2docker for low coverage files)
* reduce execution time of tests
* make a new release once Pipfile and nix support have been merged

## Soon
* the contributor highway, define the route from newcomer to project lead
* add support for using ZIP files as the repo (`repo2docker https://example.com/an-archive.zip`) this will give us access to several archives (like Zenodo) that expose things as ZIP files.
* add support for Zenodo (`repo2docker 10.5281/zenodo.1476680`) so Zenodo software archives can be used as the source in addition to a git repository
* tooling to make it easier to produce good `requirements.txt`, `environment.yml`, etc files. They should help users create versions of these files that have a high chance of still working in a few months
* support for running with GPU acceleration

## Later
* repo2docker in repo2docker, to reproduce an environment users need to specify the repository and the version of repo2docker to use. Add support for repo2docker inspecting a repo and then starting a different version of itself to build the image
* support execution on a remote host (with more resources than available locally) via the command-line

**Comment by minrk** [comment]
Nice! One challenge with using an Issue for this is that it's harder to see roadmap evolution over time than a tracked file.

**Comment by betatim** [comment]
Good point. I had not thought that we might need/want that. What would we do with that information? If we use a file should we update it in a destructive way (use git history for history) or more like a change log which is prepend only?

The use cases I had considered is:
* as a user I want to know what is coming next
* as a contributor I want to know where to get involved
* as a contributor I'd like to know what has been purposefully postponed to later
* as a maintainer I want to build consensus around the direction we want to go in the next few weeks

**Comment by choldgraf** [comment]
I have a few concerns about using a github issue for roadmaps: 

1. It is super non-discoverable. I think roadmaps are half for the developer team, half for the non-developer (or potential developer) community. Github issues will quickly fall off of the top page, which means they're virtually invisible to anybody not explicitly looking for them.
2. It is not easy to collaboratively edit. Often folks don't feel comfortable editing the comments of somebody else, and our only other option here is for you to manually re-update the top-level comment each time something changes.
3. It is very github-focused. Which is fine if roadmaps are only for developers, but IMO they are not only for developers. I want our roadmap displayed in a non-github fashion somewhere (e.g., the documentation)
4. As Min suggests, it obfuscates provenance around how the roadmap changes, and who made those changes.

Maybe some of these could be worked around if we advertised the roadmap heavily on, e.g., the repo2docker documentation and jupyter.org, but I feel like having it in proper document form would be a better long-term solution. Happy to hear arguments to the contrary!
