### ISSUE TITLE
Add labels for repo2docker version and repo 

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#466]
it would be handy to add the labels for repo2docker version, repo URL, and ref to images when we build them:

```docker
LABEL repo2docker.version="x.y.z"
LABEL repo2docker.repo="https://..."
LABEL repo2docker.ref="abc123"
```

This records in docker image metadata info about what was built, which could be useful in the future.

**Comment by betatim** [comment]
Good idea.

Do we consider the information in `repo` private? It could be a path on the users local filesystem or to some private repository which would get exposed if people build and then share the image. I could also see the argument that if you are sharing the image with someone it should be fine if they can see this information.
