### ISSUE TITLE
repo2docker blog post

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#485]
To my knowledge we've never released a repo2docker-specific blog post (we've released posts about Binder, and about JupyterHub, and we've mentioned it, but never had a specific post). Since repo2docker has grown and matured quite a bit, why don't we give a shot at telling the world about it? :-)

Since I was flying back to California for 5 hours, I figured I'd give a whirl at writing one up. Anyone have objections to releasing it whenever we cut the next release of r2d?

**Here's the latest draft, the plan is to post it on Friday the 14th**

https://blog.jupyter.org/introducing-repo2docker-61a593c0752d

cc @betatim who mentioned this might be a good idea

**Comment by WillKoehrsen** [comment]
I don't want to steal anyone's thunder, but I also wrote a short post on my blog: [Docker for Data Science Without the Hassle](https://medium.com/@williamkoehrsen/docker-without-the-hassle-b98447caedd8). Let me know if I've made any mistakes or you want me to take down the post. Hopefully, it helps raise awareness of the project!

**Comment by betatim** [comment]
Thanks, it is a great post :)

I'll close this issue as both posts are out now so our work here is done I think.

**Comment by choldgraf** [comment]
love it @WillKoehrsen !

**Comment by WillKoehrsen** [comment]
Thanks for all the work your team has done!
