### ISSUE TITLE
Manifest and Project .toml files in Julia Buildpacks

### ISSUE THREAD

**Issue by jzf2101** [jupyter/repo2docker#486]
@jekbradbury suggested we include https://docs.julialang.org/en/v1/stdlib/Pkg/index.html#Glossary-1 in our buildpacks.  Thanks @jekbradbury !

**Comment by betatim** [comment]
This came up in discussions in https://github.com/jupyter/repo2docker/pull/393 as well. Worth reading them if you want to get started on adding this.
