### ISSUE TITLE
repo2docker 0.7.0

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#489]
Should we get a new release out? I think we should get in the habit of releasing instead of the current habit of waiting for a new release. After all it is approximately free to make a release and it has been about 3months since the last release.

There is a good set of new features in the change log. One thing I originally suggested we'd wait for Pipfile support (see #447) could also wait till the next release.

Anything else you are currently working on and would substantially improve the release?

* #447 won't be done before releasing
* #478 has been merged (whoop!)
* jupyterhub/mybinder.org-deploy#865 has been merged/fixed
* #475 should be included in the release

Once #475 is merged: go time for a new release.

Post-release:
* https://github.com/jupyter/repo2docker/issues/489#issuecomment-446147399

**Comment by betatim** [comment]
Might be worth waiting to see how https://github.com/jupyterhub/mybinder.org-deploy/issues/865 gets resolved before releasing.

**Comment by yuvipanda** [comment]
Hopefully #478 too :)

**Comment by yuvipanda** [comment]
But, earlier than latter!

**Comment by minrk** [comment]
Once we make a release, it would be good to update the default repo2docker tag to 0.7.0 in binderhub.

**Comment by betatim** [comment]
https://github.com/jupyter/repo2docker/releases/tag/0.7.0

Should appear on PyPi soon.

Once we bump BinderHub's default version we can close this issue.

**Comment by choldgraf** [comment]
it'd also be nice to get this blog post out the door: https://blog.jupyter.org/introducing-repo2docker-61a593c0752d

**Comment by minrk** [comment]
blog and release made. yay, folks!
