### ISSUE TITLE
Document our expectations of people writing Dockerfiles (for now)

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#5]
What I can remember...

1. You need to explicitly do a 'COPY . $HOME' if you want your files in the final build.
2. notebook and jupyterhub-singleuser (of appropriate version matching the jupyterhub version, which you can get from the build arg $JUPYTERHUB_VERSION) must be in $PATH.

**Comment by choldgraf** [comment]
this is documented in https://mybinder.readthedocs.io/en/latest/dockerfile.html
