### ISSUE TITLE
repo2docker not found on PATH

### ISSUE THREAD

**Issue by mryap** [jupyter/repo2docker#506]
I follow the instruction at https://repo2docker.readthedocs.io/en/latest/usage.html

`jupyter-repo2docker https://github.com/norvig/pytudes`

But I got a `bash: jupyter-repo2docker: command not found`

![image](https://user-images.githubusercontent.com/15719191/50049147-70157800-00d5-11e9-8ea1-e4ebd100822b.png)

docker info
Containers: 8
 Running: 2
 Paused: 0
 Stopped: 6
Images: 9
Server Version: 18.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 114
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.06.0-ce (TCL 8.2.1); HEAD : 1f40eb2 - Thu Jul 19 18:48:09 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: default
ID: 66TB:KSLB:QLIJ:XGMY:6VMK:ZFKS:636A:257S:O5KK:ELYA:L45E:2FEV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/

Thank You

**Comment by betatim** [comment]
Two questions to help debug this:
* Which version of repo2docker did you install?
* How did you install repo2docker?

**Comment by mryap** [comment]
This time round I manage to install repo2docker in a Conda env

When I run `jupyter-repo2docker https://github.com/norvig/pytudes`,  I got this 

`Docker client initialization error. Check if docker is running on the host.
Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))`

![image](https://user-images.githubusercontent.com/15719191/50171512-906a5000-02ea-11e9-9097-cf9f731a339f.png)

**Comment by NateZimmer** [comment]
I had this issue. Restarting my shell worked for me.

**Comment by betatim** [comment]
Seems like this issue has been resolved. Closing the ticket now.

In general we recommend to post support questions over at discourse.jupyter.org. The forum has a lot more users/viewers than the issue tracker and it is better indexed by search engines. We try and keep the GitHub issue tracker for technical discussions on how to chaneg the software.
