### ISSUE TITLE
repo2docker generated notebook image crashes on Jupyterhub

### ISSUE THREAD

**Issue by slejdops** [jupyter/repo2docker#549]
I'm trying to run a Jupyter notebook image generated with repo2docker 
The docker image was built by circleci , the git repo is 
 https://github.com/malariagen/datalab-image
I used the https://jupyterhub.github.io/helm-chart/  --version=v0.8-80a76ac to deploy Jupyterhub.

The notebook container crashes with the following error message :
 [Warning] Error: failed to start container "notebook": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./start\": stat ./start: no such file or directory"

The container runs fine when started on mybinder.org,  my local machine (Ubuntu 18.04) and a Google cloud VM (also Ubuntu 18.04).

**Comment by betatim** [comment]
My guess is that when you run the image in JupyterHub the working directory is set to a directory that doesn't contain the `start` script. As a result the script can't be found in the local directory when the container starts.

**Comment by slejdops** [comment]
Thanks.
When I remove `start` from the git repo the notebook container starts on JupyterHub but none of the files in the repo get copied to the home directory - /home/jovyan.
What might be causing that ?

**Comment by betatim** [comment]
JupyterHub (deployed on kubernetes I assume?) mounts a new volume to `/home/joyvan` and that overwrites/hides what is in that directory.

There is a start of support for having repo2docker copy the contents of the repository to somewhere else in the image: https://github.com/jupyter/repo2docker/blob/ff894f4404a9abcbb5163f638f952a1ba89fe8b3/repo2docker/buildpacks/base.py#L100-L103

@yuvipanda how would I specify the REPO_DIR arg on the repo2docker command-line?

**Comment by yuvipanda** [comment]
@betatim you can specify it with `--target-repo-dir`

**Comment by slejdops** [comment]
Thanks @betatim, closing issue.
