### ISSUE TITLE
Package order in requirements.txt

### ISSUE THREAD

**Issue by fmaussion** [jupyter/repo2docker#553]
I'm trying to switch from a conda env to a pip env for building our mybinder containers. My hope is that this will speed-up the image launch for our users, because pip envs are much lighter than conda envs.

There is an issue, however. [pip does not guarantee the install order in requirements.txt](https://github.com/pypa/pip/issues/3480), which is silly but leads to situations where package won't install because numpy isn't installed (yet) although present in `requirements.txt`.

[there has been a recent PEP addressing the issue](https://github.com/pypa/pip/issues/5761) but this requires the package maintainers to update their `setup.py`, but obviously this hasn't been taken care of everywhere yet.

Any idea how to proceed in repo2docker for the time being?

**Comment by fmaussion** [comment]
I guess the way to go is to use a postBuild file then - sorry for the noise, closing the issue

**Comment by betatim** [comment]
Link to PEP518 https://www.python.org/dev/peps/pep-0518/ for the curious.

`postBuild` will work though I'd treat it as a workaround while waiting for PEP518 support. Might be worth making a PR to the packages you use to see if they are interested in adding PEP518 support.
