### ISSUE TITLE
Consider removing versioneer?

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/repo2docker#558]
I've had nothing but trouble with it when installing repo2docker from master or from a specific branch. For example, if you do:

```
pip install git+https://github.com/yuvipanda/repo2docker@julia-requirements
```

It thinks the version is `jupyter-repo2docker-0.2.0+1064.ga3b7e95` which isn't true, and causes lots of other failures in other projects that depend on `jupyter-repo2docker>0.7`. There's also no easy way for me to debug this.

What value do we get from this somewhat large piece of code? Can we just use manual versioning instead?

**Comment by betatim** [comment]
Let's see if we can debug this. The advantages of using it:
* releasing requires creating a tag on the git CLI and pushing it
* if you are running a branch/master `repo2docker --version` will report the precise revision you are using (handy for debugging)
* i've never had to look at the code of versioneer, it seems to just work

cons:
* it is a huge amount of code
* none of us can debug it (realistically)
* sometimes versioneer breaks
