### ISSUE TITLE
'Repo2Docker' object has no attribute ‘debug'

### ISSUE THREAD

**Issue by jhamman** [jupyter/repo2docker#563]
As reported by @sbinet, 

When repo2docker raises an error, it is possible to get the following message on the command line:

```
'Repo2Docker' object has no attribute ‘debug'
```

This seems to come from this section: 

https://github.com/jupyter/repo2docker/blob/ff894f4404a9abcbb5163f638f952a1ba89fe8b3/repo2docker/__main__.py#L335-L344

I am not sure exactly how the configuration system works here but I notice this is the only time the `debug` argument is accessed:

https://github.com/jupyter/repo2docker/blob/ff894f4404a9abcbb5163f638f952a1ba89fe8b3/repo2docker/__main__.py#L220-L221

cc @betatim who thought this also looked like a bug

**Comment by yuvipanda** [comment]
I think I missed adding a 'debug' boolean traitlet to repo2docker.app when I did some refactoring...

**Comment by betatim** [comment]
Yuvi, can you please make a PR that sets `app.debug` to true when the logging level is high enough?

**Comment by yuvipanda** [comment]
@betatim done https://github.com/jupyter/repo2docker/pull/575

**Comment by jhamman** [comment]
Thanks @yuvipanda!!!
