### ISSUE TITLE
nteract not working any more?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#570]
I just tried building a new repository and running nteract, but it didn't work (got a 404 error). I tried the same with some examples on the [nteract examples repo](https://github.com/nteract/examples) and also got a 404 error.

I thought that nteract was installed by default on repo2docker, but wanted to double check that there isn't any other installation I need to do for nteract. If not, then perhaps we have a regression?

cc @rgbkrk in case he's run into any of these issues w/ Binder

**Comment by rgbkrk** [comment]
If we're getting a 404, that's the default page we'll see if an extension isn't enabled on a jupyter server.

**Comment by choldgraf** [comment]
Ya, older binders are working for me too, so maybe something has changed in repo2docker?

**Comment by rgbkrk** [comment]
On a similar note, we just released a new version of nteract for jupyter servers last night.

**Comment by rgbkrk** [comment]
We have a new version out so maybe we need to see about upgrading it in the repo2docker setup.

**Comment by choldgraf** [comment]
If you wanna make a quick PR for it I'm happy to give a merge n' deploy if we think that'll fix it :-)

**Comment by rgbkrk** [comment]
Now that we're past the hump with converting to TypeScript (and an unexpected transition to styled-components), we'll be making regular releases again so I'll keep you all posted. 😄

**Comment by choldgraf** [comment]
hmmm mybinder.org-deploy is giving me timeout errors in circle https://travis-ci.org/jupyterhub/mybinder.org-deploy/builds/486589545 :-(

**Comment by rgbkrk** [comment]
The build you linked is currently chugging along -- was that build just restarted or did it suddenly become active as I was looking?

**Comment by choldgraf** [comment]
yeah I restarted it - @yuvipanda pointed out that one of the tests was failing though https://github.com/jupyterhub/mybinder.org-deploy/pull/888#issuecomment-459109663 

not sure if it's related to the nteract bump

**Comment by choldgraf** [comment]
hey - I *think* that I got the bump working: https://mybinder.org/v2/gh/binder-examples/requirements/master?urlpath=nteract/tree/index.ipynb

this at at least no longer shows the 404 page
**however**, it seems like nteract is having a hard time connecting to a kernel?

@rgbkrk maybe that repo isn't set up for nteract properly? If you re-build your example repos do they work now?

**Comment by choldgraf** [comment]
something I noticed: the notebook metadata defines a "python2" kernel, though it isn't available in the binder environment. The original notebook UI will detect that it doesn't have the Python2 kernel and will instead load Python 3. Using nteract, and looking at the logs, I see the log saying "I don't have Python2", and then I see this:

```
{
      "Cookie": "username-hub-mybinder-org=\"2|1:0|10:1549393291|25:username-hub-mybinder-org|44:MTFhNWNjMWJiZTRkNDRkYjk4ZGU1NWEwNTg0ZTQ5YWM=|76b0b93300c8ce033c13ffc38c15bfe136d0f10be52ba062b9f811e4602529f0\"; G_ENABLED_IDPS=google; _xsrf=2|60538ea4|022590515a94a7cd149ecd8815dde6ef|1549307275",
      "Accept-Language": "en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7,mt;q=0.6",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://hub.mybinder.org/user/binder-examples-requirements-pyqwisii/nteract/tree/index.ipynb",
      "Accept": "*/*",
      "Content-Type": "application/json",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
      "X-Xsrftoken": "2|60538ea4|022590515a94a7cd149ecd8815dde6ef|1549307275",
      "X-Requested-With": "XMLHttpRequest",
      "Origin": "https://hub.mybinder.org",
      "Authorization": "token 6XkBaS2ySS-feKCSCy2Zag",
      "Content-Length": "88",
      "X-Scheme": "https",
      "X-Original-Uri": "/user/binder-examples-requirements-pyqwisii/api/sessions",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "hub.mybinder.org",
      "X-Forwarded-For": "76.102.123.61,10.12.5.75",
      "X-Real-Ip": "76.102.123.61",
      "Connection": "close",
      "Host": "hub.mybinder.org"
    }
```

So this tells me that the connection is closed upon this conflict. Is this intentional behavior, or should nteract behave the same way the original notebook UI does?

**Comment by rgbkrk** [comment]
nteract should behave the same as the original notebook UI

cc @captainsafia @stormpython

**Comment by captainsafia** [comment]
Agree with Kyle.

Can someone with permissions transfer this issue over to the nteract/nteract repo so we can track it there?

**Comment by rgbkrk** [comment]
It looks like issue transfer only works within a single org (?)

**Comment by choldgraf** [comment]
sounds good! and thanks for following up :-)

@captainsafia or @rgbkrk could you confirm that nteract does work for binder repositories that do have the correct kernel named? I wanna make sure that we get that one working!

**Comment by choldgraf** [comment]
just a note that Binder isn't able to build the nteract examples repository now, I'm not sure why :-/

I opened https://github.com/nteract/examples/issues/21 to discuss

**Comment by captainsafia** [comment]
> @captainsafia or @rgbkrk could you confirm that nteract does work for binder repositories that do have the correct kernel named? I believe I fixed it [here](https://github.com/jupyter/repo2docker/issues/570#issuecomment-460373420) but I wanna make sure that we get that one working for the example repos!

I verified that if the kernel defined in the notebook schema exists that nteract will connect to it. The problem is just when the kernel defined in the schema doesn't exist on the machine. :/

**Comment by choldgraf** [comment]
ok cool, that's good to know :-) thanks for checking it out! probably it is fairly uncommon to have a mismatch between available kernels and the notebook metadata kernel!

**Comment by choldgraf** [comment]
ok I think nteract is working again - I just tried w/ the nteract-examples repository and that worked! Closing now but feel free to open if something is still wrong!
