### ISSUE TITLE
Increasing the number of CPUs to build R packages

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#580]
via https://github.com/jupyterhub/binderhub/issues/785#issuecomment-464058205:

We could set the number of CPUs used during the building of R packages to >1 to get a speed up. However I am not sure how we would automatically determine what number to set this to. I think counting the number of cores from inside a container will give you the number of cores on the host which you might or might not be able to use. When running on k8s it would be even trickier because the resources are limited via the pod config.

My assumption is that running with a configuration of (say) ncpus=16 when really you can only use 2 cores will slow things down even more than running with ncpus=1 does.

Maybe in connection with #579 we can set it when we know what the user set the limit to?

related: #412

**Comment by choldgraf** [comment]
mmmm I don't know that much about how to check for the CPU power available and request something different depending on what's returned. This feels like it'd be pretty tricky to debug or maintain, no?

**Comment by choldgraf** [comment]
@betatim how do you feel about this one? `dontfix`? Or worth discussing more?
