### ISSUE TITLE
Support julia 1.1

### ISSUE THREAD

**Issue by davidanthoff** [jupyter/repo2docker#582]
It seems that julia 1.0 is supported, but not julia 1.1. Would be great to have support for 1.1 as well.

**Comment by betatim** [comment]
Indeed! Do you want to open a PR for that?

**Comment by davidanthoff** [comment]
I'm afraid I won't be able to open a PR for that (overcommitted already, plus adding a PR to a project I'm not familiar with at all is typically a lot of work). BUT, I would be very grateful if someone else did :)

**Comment by betatim** [comment]
> BUT, I would be very grateful if someone else did :)

Wouldn't we all 😂

**Comment by betatim** [comment]
This would be a good first issue to tackle to get into the project. It should be straight forward to add an additional version of Julia as we can copy what is done for Julia 1.0.

**Comment by NHDaly** [comment]
Thanks @davidanthoff
