### ISSUE TITLE
Switch to pip 19.0.3

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#589]
After releasing v0.8.0 we should check if pip 19.0.3 fixes the problem that we worked around with #574.

**Comment by LucianaMarques** [comment]
Hi there, can I work on this issue?

**Comment by betatim** [comment]
Yes please! If you start working on this it would be great if you could open a Pull Request with a title that starts with `[WIP]` (for work in progress) even if you are still some ways off from being done with it. That is how we keep track of who is working on which issue.

If you need some pointers to get started post here or stop by https://gitter.im/jupyterhub/binder.

**Comment by LucianaMarques** [comment]
> Yes please! If you start working on this it would be great if you could open a Pull Request with a title that starts with `[WIP]` (for work in progress) even if you are still some ways off from being done with it. That is how we keep track of who is working on which issue.
> 
> If you need some pointers to get started post here or stop by https://gitter.im/jupyterhub/binder.

Great! Thanks! :)
