### ISSUE TITLE
Use JULIA_LOAD_PATH for julia env handling

### ISSUE THREAD

**Issue by davidanthoff** [jupyter/repo2docker#610]
https://github.com/jupyter/repo2docker/pull/595 writes a jupyter kernel that automatically loads the `Project.toml` env that is in the root. This works, but it also means that any julia shell for example does not have the environment loaded by default, because only this particular Jupyter kernel automatically loads the env.

It might be a better strategy to instead add the root folder of the repo to the `JULIA_LOAD_PATH` env variable. I believe that should make everything to all julia processes available, not just Jupyter kernels.

I would suggest we first ship the current implementation in the PR (which is not incorrect), and then investigate this option here.

**Comment by betatim** [comment]
If that is the right thing to do from a Julia perspective I think we should do it.

I added the labels because I think this would make a good starter issue for someone new to repo2docker.

**Comment by davidanthoff** [comment]
Actually, I think we should set `JULIA_PROJECT`, see https://docs.julialang.org/en/latest/manual/environment-variables/#JULIA_PROJECT-1.

We could even set it to just `@.`, potentially... I'm playing with this now.
