### ISSUE TITLE
Rewrite semver tests to use pytest's parametrize functionality

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#615]
via https://github.com/jupyter/repo2docker/pull/613#discussion_r263836315:

> In a future refactor, we should use pytest's parameterize capability to feed in versions to get closer to DRY. [See example from JupyterHub tests](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/tests/test_proxy.py#L169).

This would make a good issue for getting started on contributing to repo2docker and/or someone who wants to learn more about pytest.

**Comment by Geektrovert** [comment]
Can I work on this issue? I'm still new to this, so a little guidance would be very nice!

**Comment by betatim** [comment]
The idea is to rewrite the [test function that Carol's commented on](https://github.com/jupyter/repo2docker/pull/613#discussion_r263836315) to have one line of code instead of lots of lines that are the same except for the values that are being tested. We'd pass inn the many different values and the expected answer via [this mechanism](https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions).

**Comment by Geektrovert** [comment]
@betatim some code coverage is failing!

<img width="669" alt="Screenshot 2019-08-02 at 7 23 43 PM" src="https://user-images.githubusercontent.com/13296694/62373263-39547b00-b55b-11e9-997c-a2c86cfa62b5.png">

<img width="1162" alt="Screenshot 2019-08-02 at 7 25 59 PM" src="https://user-images.githubusercontent.com/13296694/62373339-6143de80-b55b-11e9-8615-17ed8c784965.png">

Is that related to the code I've changed? Is there anything I should solve?
