### ISSUE TITLE
black based autoformatting

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#616]
I'd like to propose we follow JupyterHub's lead and adopt black as commit hook and use it to format our code.

https://github.com/jupyterhub/jupyterhub/issues/2416

I'm not sure we need to go as far as JupyterHub and sort imports etc, just using black as a pre-commit hook seems like a good compromise.

It will cause a bit of disruption/code churn so I think we should schedule it for some time in the future so we can merge or close as many outstanding PRs as possible to minimise the number of "nothing but formatting" commits.

What do people think?

**Comment by choldgraf** [comment]
I'm +0 on this - could go either way...

**Comment by choldgraf** [comment]
What's our path forward on this one? Perhaps it's worth discussing at the next team meeting so we can get a quick feedback on it?

Also a clarifying question: would this basically be a matter of adding something to this repository, and then git would automatically do this any time a commit was made?

**Comment by betatim** [comment]
> Perhaps it's worth discussing at the next team meeting so we can get a quick feedback on it?

I think the lack of comments means no one has a strong opinion on this. I am +1 you are +0 so I'll make a PR that sets things up similar to the JupyterHub repo.

> Also a clarifying question: would this basically be a matter of adding something to this repository, and then git would automatically do this any time a commit was made?

We would add a pre-commit hook that executes locally when you commit things as well as some checks in the CI job. It means adding a step to the contributing guide as people need to install the precommit hook and a short explanation of what is happening.

**Comment by choldgraf** [comment]
does this mean any new contribution to the package would require the person to first install black?

**Comment by betatim** [comment]
You need to install https://pre-commit.com/ which takes care of configuring all the pre-commit hooks. 

I think you can still commit without installing it but the CI tests would tell you off if you didn't format the code properly.

**Comment by choldgraf** [comment]
So this is basically a combination of:

1. Install a code formatter as a part of the tests (in this case, Black, but using `flake8` is a pretty common pattern so I don't see a problem with this)
2. Suggest that it'll be easier to people if they install a commit hook to auto-blackify things.

I do think this is going to create labor for maintainers and contributors for any new PR (I bet many will forget to format in Black before pushing), but I'll defer to y'all about the added benefit we'd get from having this run automatically, since I've never used Black before. To me that's the question: is the extra annoyance/over-head associated with adding a new step to push a commit overpowered by the benefit we'd get at having Black code standardization?

**Comment by betatim** [comment]
> How much extra burden/trickyness are we introducing?

I think one way to find out for yourself is to try and follow https://github.com/jupyterhub/jupyterhub/blob/master/CONTRIBUTING.md#setting-up-a-development-environment which talks you through it. To me it doesn't seem like a bit deal, but I don't think I'm a representative sample here.

For maintainers/PRs it should reduce the toil because as a reviewer you don't need to think about formatting/PEP8/linting any more because travis will do it for you and put a red cross on the PR.

I dislike some of the formatting choices black makes on a personal taste level, but the benefit of having code be uniformly formatted outweighs my taste. It makes it so much nicer. A bit like when you got used to working in a kitchen where everything has its precise place and go back to your messy not-at-all-pro kitchen where you can find stuff but it takes 20s longer.

**Comment by choldgraf** [comment]
I'll give it a shot myself to see how it feels (though I probably am not representative either)

**Comment by choldgraf** [comment]
Just a note that I ran into this error:

```
Output:
    Using base prefix '/home/choldgraf/anaconda/envs/dev'
    New python executable in /home/choldgraf/.cache/pre-commit/repo9ae_jgxz/py_env-python3.6/bin/python3.6
    Also creating executable in /home/choldgraf/.cache/pre-commit/repo9ae_jgxz/py_env-python3.6/bin/python
    ERROR: The executable /home/choldgraf/.cache/pre-commit/repo9ae_jgxz/py_env-python3.6/bin/python3.6 is not functioning
    ERROR: It thinks sys.prefix is '/' (should be '/home/choldgraf/.cache/pre-commit/repo9ae_jgxz/py_env-python3.6')
    ERROR: virtualenv is not compatible with this system or executable
    Running virtualenv with interpreter /home/choldgraf/anaconda/envs/dev/bin/python3.6

Errors:
    /home/choldgraf/.cache/pre-commit/repo9ae_jgxz/py_env-python3.6/bin/python3.6: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

will try and figure it out, maybe it's related to me being on WSL or something (I dunno why it says the `sys.prefix` is wrong)

**Comment by choldgraf** [comment]
Just a note, the Django community recently had a DEP about black that I found quite helpful https://github.com/django/deps/blob/master/accepted/0008-black.rst

**Comment by choldgraf** [comment]
Looking into it a bit more, and I am coming around to the idea of black :-)

As a reference, I ran the default black command and opened a PR here to look at the diff: https://github.com/jupyter/repo2docker/pull/680/files

How do people feel about separating out the "black validator as part of test suites" part from the "black as a pre-commit hook". I think setting up the pre-commit hook was annoying to do on my side (I still haven't figured it out) and is kind of orthogonal to the "what format should our code have" question.

## What if we did this:

* Create a PR that we immediately merge that simply runs the default black command on the repo, that's it.
* Create another PR that adds `black --check` to our test-suite so the tests fail if we break black
* Create a third PR that adds an optional "how to use black as a pre-commit hook" part to the documentation

As long as the pre-commit thing isn't a strictly-required thing for developers, I'm +1 on this

**Comment by betatim** [comment]
I would make one PR that installs `black --check` as part of our CI as well as any config (like line length) and a second commit that contains the changes from running `black .` on the code base. If we make two PRs we just risk someone merging something that isn't black formatted.

For the pre-commit docs I think we can take step 5 from https://github.com/jupyterhub/jupyterhub/blob/master/CONTRIBUTING.md and also do that in that one PR? Was there more you needed to do to get things working Chris?

**Comment by choldgraf** [comment]
nope that sounds right to me

**Comment by yuvipanda** [comment]
One thing I'd love is a bot you can invoke on a PR that'll make a commit to that PR that autoformats it with black. So on a PR you'd be like 'hey @autoblackbot, please reformat this PR'. It'll swoop in, make a commit and *push it to the PR*. This makes it possible for people who are first time contributors to make drive-by contributions with less hassle than otherwise.

Absolutely not a blocker for adoption though.

**Comment by choldgraf** [comment]
The bot idea sounds great and I agree it shouldn't be a blocker. Maybe something that Meeseecks could help with? (cc @Carreau)

**Comment by betatim** [comment]
On the auto-formatting front: on scikit-optimize we (used to) use the `pep8speaks` bot that comments and can [make a PR against a PR to pep8-ify it](https://github.com/OrkoHunter/pep8speaks#miscellaneous-features). It already supports multiple backends so maybe it can be extended to support black, and someone else is already operating that bot as a service.

**Comment by Carreau** [comment]
pep-8-speak would be good. 
I would wait a tiny-bit; black is close to being 1.0 (closer than jupyterlab maybe).

Note that auto-applying black can be a bit tricky for new contributors that would need to pull for every change we asked them to do. 

One possibility would be a way to run-black-and-merge. 

if you use black on the repository and it does major reformatting, you can use [git hyper-blame](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html) to skip the refactoring commits.

**Comment by choldgraf** [comment]
so, what shall we do here? We've got https://github.com/jupyter/repo2docker/pull/680 waiting although that'll start to get out of date. Should we wait until it hits 1.0-levels of stability? I'm fine with that if it really won't be long...but I have heard that projects tend to get bogged down just before releasing 1.0.... ;-)
