### ISSUE TITLE
support .binder instead of binder as config directory

### ISSUE THREAD

**Issue by rabernat** [jupyter/repo2docker#617]
I would like to use the path`.binder/` rather than `binder/` for my [repo](https://github.com/pangeo-data/pangeo_ocean_examples) configuration. I read the docs but couldn't figure out if it is supported to change the config path. I tried it and I think it did not work.

**Comment by betatim** [comment]
Currently not supported.

**Comment by choldgraf** [comment]
hey @rabernat - could you explain more why you want to use `.binder` instead of `binder/`?

**Comment by jhamman** [comment]
I'm +1 on a change like this. It would be nice to have the option to "hide" the binder directory from the user. I think this is less of an issue for the Binder use case but for uses of repo2docker outside of Binder, the `binder` directory can be distracting. I think the use case @rabernat and I are are both thinking of is when we use repo2docker to build custom images for our JupyterHub deployments.

**Comment by betatim** [comment]
I think supporting both `.binder` and `binder` could be interesting and worth exploring with a PR.

What kind of feedback do you get from users when they are confused/distracted by this? One good thing about it being explicit is that it makes it (more) obvious how the environment was crafted and how to recreate it yourself at home.

**Comment by choldgraf** [comment]
it sounds like @jhamman is imagining this in the context of jupyterhub rather than binderhub (e.g. using a github repo to define the environment + files, but not necessarily in the context of a reproducible analysis etc)

**Comment by betatim** [comment]
One solution to "my users are confused" is to add a `postBuild` line that does `rm -rf binder/` to remove all traces of how the repo was created :) You could also add that to an appendix for your repo2docker run so that you don't have to put it in each repo.

**Comment by consideRatio** [comment]
It is very typical, for example .circleci etc, that build configuration stuff is in hidden files and folders. Since it has been done with the nonhidden binder folder up until now, i also think a pr to support both would make sense.

**Comment by choldgraf** [comment]
I'm +1 on supporting a hidden folder called `.binder`

**Comment by jhamman** [comment]
I've opened PR #653 to add support for the `.binder` directory.
