### ISSUE TITLE
ENH: generate a dockerfile instead of a docker image

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#62]
It might be useful for people to use r2d to generate dockerfiles instead of images...could be a flag or something

**Comment by choldgraf** [comment]
Two quick questions for @yuvipanda :

1. how would we handle something like postBuild scripts? just not support them? 
2. Looking through the code it seems like [here](https://github.com/jupyter/repo2docker/blob/master/repo2docker/detectors.py#L390) is where we'd put the switch to dump out a dockerfile instead of the image...that sound correct?

**Comment by yuvipanda** [comment]
postBuild is unaffected by this.

Nope not right place. You would just call the tender method and not the
build method.

**Comment by choldgraf** [comment]
hm....not sure what that means, I don't see any methods called `tender` in there, maybe I'm missing something?

**Comment by yuvipanda** [comment]
Late night bathroom break GitHub comments plus autocorrect is what you are
missing :D

The method is called 'render'

**Comment by choldgraf** [comment]
lol :-P

**Comment by choldgraf** [comment]
thank you for confirming that I'm not nuts haha...I was like WTF WHERE IS THIS TENDER CODE?!?!

**Comment by yuvipanda** [comment]
This can happen now :)

**Comment by choldgraf** [comment]
Can we leave this open until we've got it documented? :-)
