### ISSUE TITLE
IJulia kernels installed in $HOME not /srv

### ISSUE THREAD

**Issue by rabernat** [jupyter/repo2docker#620]
I am using the latest repo2docker to install a Julia env using a Project.toml file ([binder config here](https://github.com/pangeo-data/pangeo-stacks/tree/master/pangeo-ocean/binder)).

I find that the IJulia kernels are installed in my home directory
```bash
$ jupyter kernelspec list
Available kernels:
  julia-1.1    /home/jovyan/.local/share/jupyter/kernels/julia-1.1
  python3      /srv/conda/share/jupyter/kernels/python3
```

It would be better if it were installed in `/srv` next to the python kernel. In particular, this causes problems in JupyterHubs which mount other volumes in $HOME; in that case the julia kernelspec disappears.

Examining the [IJulia install script](https://github.com/JuliaLang/IJulia.jl/blob/master/deps/kspec.jl), it looks like we could fix this by setting either the environment variable `JUPYTER_DATA_DIR=/srv/conda/share/jupyter` or `XGD_DATA_HOME=/srv/conda/share/jupyter`.

This issue is very similar to, but distinct from, #554.

**Comment by betatim** [comment]
cc @NHDaly and @davidanthoff as resident Julia experts.
