### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by davidanthoff** [jupyter/repo2docker#625]
I just saw https://github.com/codercom/code-server, which at a first look might be a pretty cool match for binder?

**Comment by ryanlovett** [comment]
Yep!

https://mybinder.org/v2/gh/betatim/vscode-binder/master?urlpath=lab

([via](https://twitter.com/betatim/status/1106195567892402177))

**Comment by davidanthoff** [comment]
Insane and awesome!! And I'll close this, I guess @betatim did all the work already :)

**Comment by betatim** [comment]
Most of the work is in the code-server repo/project. I think we should watch how it develops and when it looks stable and "good" investigate if we can install it by default as part of repo2docker, like we install RStudio.

Right now there are still some issues like missing icons and such, so I'd wait for code-server to improve a bit more.

**Comment by sanjaydatasciencedojo** [comment]
How do I use to create a notebook image that is compatible with Jupyterhub?
