### ISSUE TITLE
build the docker image raise a pip error

### ISSUE THREAD

**Issue by shaoliming1** [jupyter/repo2docker#630]
![image](https://user-images.githubusercontent.com/48719416/55070534-74343700-50c1-11e9-9533-54ba7c304294.png)

-->

**Comment by betatim** [comment]
Do you have a link to the repository you are trying to build?

**Comment by shaoliming1** [comment]
https://github.com/shaoliming1/repo2dockder------------------ Original ------------------

**Comment by betatim** [comment]
From a quick look it doesn't look like a technical problem in repo2docker but a support question about the particular combination of packages. The best place for those kinds of questions is https://discourse.jupyter.org/c/questions, please create a post there with the above information. Thanks a lot!

**Comment by shaoliming1** [comment]
thank you very much!------------------ Original ------------------
