### ISSUE TITLE
Adding my own content provider

### ISSUE THREAD

**Issue by shibbas** [jupyter/repo2docker#634]
Hi, 

Was wondering if I can load content from a non-github repo dynamically? Should I be creating a new content provider to do this? If so, does that mean I need to update all the dependency files with any needed packages, or can these be loaded dynamically at runtime?

**Comment by betatim** [comment]
To load content from a place that isn't a git repository or a local directory content providers are the way to go. Where would you like to fetch things from?

> does that mean I need to update all the dependency files

You'd have to update `setup.py` and `requirements.txt` to add the packages your new content provider needs.

I am excited to see a new content provider! It will be the first new one ever! 😀

**Comment by shibbas** [comment]
Thanks! For standard project locations like git or a remote tar ball, i think it makes total sense to introduce a baked in content provider. I was thinking more along the lines of non-standard project locations like azure storage. This would mean introducing azure packages which would not be needed for anything other than the content provider, so was wondering if there is dynamic way to introduce a new content provider instead of baking in the list. Sounds like there isn't?

**Comment by betatim** [comment]
Currently there isn't a way to create content providers that aren't part of the repo2docker code base. There is #488 though where I mention entrypoints as a way to do this. They are used in https://github.com/nteract/papermill to allow people to extend things without having to add everything to the core repository.

It would be super cool to extend repo2docker to have a plugin mechanism for content providers based on entrypoints. But it does mean some work before the actual work on the AZ content provider.

**Comment by shibbas** [comment]
Interesting that papermill already does that. Yeah, would be great to have this. I will think about this scenario more... Thank you for the information!

**Comment by betatim** [comment]
Should we close this issue then? It seems to me the next step would be to open a PR if you wanted to work on this but we don't need this issue anymore really.

**Comment by shibbas** [comment]
Agreed. Closed!
