### ISSUE TITLE
Cleaning out /srv/conda/pkgs

### ISSUE THREAD

**Issue by rabernat** [jupyter/repo2docker#636]
We are using repo2docker to build a fairly big python data science environment. (Image repo: https://github.com/pangeo-data/pangeo-stacks/tree/master/pangeo-notebook)

The compressed, built image is currently over 1GB in size. (docker hub: https://hub.docker.com/r/pangeo/pangeo-notebook/tags)

We would like the docker image to be smaller if possible. I noticed that there is currently about 2.6GB residing in `/srv/conda/pkgs`.

```
$ du -h -d0 /srv/conda/pkgs
2.6G    /srv/conda/pkgs
```

Is the expected behavior? If so, what would be the recommended way to clean this directory from my repo2docker build?

**Comment by betatim** [comment]
I don't know enough about the insides of conda to be super sure but a quick google found me https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/xV1BiGPmgao which makes me think that repo2docker should wipe this directory.
