### ISSUE TITLE
Give the Binder repository spec a name

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#656]
We've had a [few conversations about an open standard for reproducible repositories](https://discourse.jupyter.org/t/creating-a-specification-for-reproducible-repositories/569). I think it'll take a while for that all to settle out, but in the meantime could we name the specification that Binder uses to build a repo's environment. Even if that spec changes, we could start using it in docs, presentations, etc. Something like **The [Binder] Reproducible Repository specification**.

Then rather than saying "A Binder-ready repository is a repository that can be built with repo2docker without an error" we could say "A Binder-ready repository is a repository that follows the (link to) Binder reproducible repository specification".

**Comment by betatim** [comment]
I'd be happy with naming it "the reproducible repository specification". Maybe one tweak is how do we name it to not exclude things like a zenodo or other thing that isn't a repository (in the programmer sense)? "Reproducible directory spec", which is a bit weird I think. Sounds like the directory is reproducible, not that its contents leads to a reproducible environment in which code can be executed.

Maybe in that spirit: "reproducible execution environment spec"?

**Comment by choldgraf** [comment]
Nice - what about just "Reproducible Environment Specification"?

Or we could confuse the UK folks and call it the "Specification for Reproducible Environments" (or SRE for short ;-) )

**Comment by choldgraf** [comment]
OK, thinking about it again, I am +1 on

**Reproducible Execution Environment Specification**

anybody else have thoughts?

**Comment by betatim** [comment]
Sounds good to me.

We can always change the name if we really hate it. More important is to have a couple of paragraphs to layout what the pieces of the REES are. What areas will it address and which won't it address kinda thing. Maybe we can turn it into docs and a short blog post together with the release?

**Comment by choldgraf** [comment]
lemme know what you think about #662
