### ISSUE TITLE
Releasing v0.9.0

### ISSUE THREAD

**Issue by betatim** [jupyter/repo2docker#658]
Now that we have conda 4.16 and `.binder/` support, should we make a new release?

It has been nearly three months since v0.8.0 and there are quite a few other changes/features so I think we should do it.

Is there an open issue/PR that should be landed first?

I'd get these in:
* [x] #655 
* [x] #657 -> change log
* [x] #652 -> change log
* [x] #656 -> change log
* [x] update change log

(issues/PRs with a `-> changelog` after them need to still be added to the change log)

**Comment by betatim** [comment]
Does anyone else have input or opinions on this?

@choldgraf do you think we can converge on a name in #656 within the next 24h? Otherwise I'd make a release without waiting as I think it would only feature in the change log as a note. Alternatively if we plan to build on the naming discussion with some documentation etc then we should release now and include that in the next release (as it'll take days or weeks to build docs).

**Comment by choldgraf** [comment]
Just noticed this PR, if it helps move things forward, I'm happy to table #656 until .10.0, though I'm also happy to put in the conversation time to come up with a name, I think we are close!

**Comment by choldgraf** [comment]
@betatim you've made the last several releases, would you like me to give this one a shot?

**Comment by betatim** [comment]
Yes please! Just looked at https://repo2docker.readthedocs.io/en/latest/contributing/tasks.html#creating-a-release and I think it is up-to-date and what I did last time.

**Comment by betatim** [comment]
There is one thing missing: after you create and push the tag you need to add the release on https://github.com/jupyter/repo2docker/releases

**Comment by choldgraf** [comment]
I think (?) we're ready to go on #662 and #664 ... once those are in (or once we decide to postpone) I will try making a release.

**Comment by betatim** [comment]
I think we are ready to do. @choldgraf remember you need to make one last PR before tagging the release where you update the date. Feel free to self-merge that PR (please don't try and push directly to master in this repo :) )

**Comment by choldgraf** [comment]
OK, I followed the instructions in https://github.com/jupyter/repo2docker/pull/668. Tagged, pushed, and cut a new release on github. I'm waiting for travis to finish to confirm a new version has been published to PyPI (I'm assuming we don't need to do anything other than push the tag and it "just happens")

**Comment by betatim** [comment]
https://pypi.org/project/jupyter-repo2docker/ we are live!

Congrats on making your first release of repo2docker! Thanks everyone for your time and brain cycles in building this latest release.
