### ISSUE TITLE
conda clean command line arguments discussion

### ISSUE THREAD

**Issue by consideRatio** [jupyter/repo2docker#667]
I noticed repo2docker use the same command line arguments as jupyter/docker-stacks for `conda clean`. I initiated a discussion about these flags in this issue on docker-stacks: https://github.com/jupyter/docker-stacks/issues/861

Perhaps related: #666

**Comment by betatim** [comment]
Thanks for the pointer. I'll close this issue again to keep the discussion either in #666 or (better)  jupyter/docker-stacks#861.
