### ISSUE TITLE
Add a hook for injecting files to tarfile with a Docker build context

### ISSUE THREAD

**Issue by Xarthisius** [jupyter/repo2docker#673]
### Proposed change
I'd like to propose adding a hook that would allow to add files directly to the tarfile that's used as a Docker build context. See: https://github.com/jupyter/repo2docker/blob/d674eceeba77ec3fd16b7123bf248b0aede2bf7e/repo2docker/buildpacks/base.py#L493-L521

Right know, there's an implicit assumption that all files injected to the context are a part of r2d itself:

https://github.com/jupyter/repo2docker/blob/d674eceeba77ec3fd16b7123bf248b0aede2bf7e/repo2docker/buildpacks/base.py#L516

### Rationale
This feature is useful(/necessary) for developing custom buildpacks as repo2docker plugins (following @yuvipanda's suggestion: https://github.com/jupyter/repo2docker/issues/487#issuecomment-479794426) in case they need to inject their own script files.

### Alternative options
Alternative, would be to somehow modify base template and `get_build_script_files` to take into account that files can reside outside of repo2docker repository. However, this sounds a lot more invasive.

### How much effort will adding it take?
Not much, because I'm a lazy bum:
```diff
--- a/repo2docker/buildpacks/base.py
+++ b/repo2docker/buildpacks/base.py
@@ -488,6 +488,10 @@ class BuildPack:
             appendix=self.appendix,
         )
 
+    def add_files_to_docker_context(self, tar, filter=None):
+        """Inject files directly to the tar file used as the Docker build context."""
+        pass
+
     def build(self, client, image_spec, memory_limit, build_args, cache_from, extra_build_kwargs):
         tarf = io.BytesIO()
         tar = tarfile.open(fileobj=tarf, mode='w')
@@ -514,12 +518,15 @@ class BuildPack:
         for src in sorted(self.get_build_script_files()):
             src_parts = src.split('/')
             src_path = os.path.join(os.path.dirname(__file__), *src_parts)
-            tar.add(src_path, src, filter=_filter_tar)
+            if os.path.isfile(src_path):
+                tar.add(src_path, src, filter=_filter_tar)
 
         tar.add(ENTRYPOINT_FILE, "repo2docker-entrypoint", filter=_filter_tar)
 
         tar.add('.', 'src/', filter=_filter_tar)
 
+        self.add_files_to_docker_context(tar, filter=_filter_tar)
+
         tar.close()
         tarf.seek(0)
```

### Who can do this work?
I volunteer as a tribute!

**Comment by yuvipanda** [comment]
I thought get_build_script_files already supported this, but it does not!

```python
        for src in sorted(self.get_build_script_files()):
            src_parts = src.split('/')
            src_path = os.path.join(os.path.dirname(__file__), *src_parts)
            tar.add(src_path, src, filter=_filter_tar)
```

So we make all paths here relative to the repo2docker package dir. I think this was done here as a convenience. I think we should modify it to be:

1. If a relative path (doesn't start with /) is given, keep current behavior.
2. If an absolute path is given (starts with /), don't do any path mangling.

I think this wouldn't be too invasive, and help you accomplish what you want in the stage of the buildpack you'd like. 

Does that work?

**Comment by Xarthisius** [comment]
That would work, but there is a caveat: There are actually three paths:
1. physical path of the file outside of build context
2. path of the file in the build context
3. path where the file is copied from the build context to the container.
Coincidentally (or by design) relative path used in 1. is equal to 2. in r2d. When you start using absolute path it will break that assumption, which is implicitly used in other places.

**Comment by Xarthisius** [comment]
@yuvipanda correct me if I'm wrong, but AFAICT in order to support absolute path I'd need to make the following changes:

1. Convert `get_build_script_files` to output files in a format that would account for all paths, e.g.:
  ```
  {
      'path_to_file_in_build_context': ('path_to_file_on_host', 'dest_path_in_the_container')
  }
  ```
2. Modify base template to take 1. into account:
  ```
  COPY {{ src }} {{ dst[1] }}
  ```
3. Modify `BuildPack.build` to use new format of `get_build_script_files`.

Do you want me to proceed with that?

**Comment by yuvipanda** [comment]
Hmm, that's a good catch! I'll admit to not having thought about that.

What do you think about this:

1. Keep the mapping be `'path_in_host': 'path_in_container'`
2. *Generate* filenames for all `path_in_host`, maybe with converted path + a hash. Put the files under generated filenames into the build context
3. Modify the Dockerfile generated to use the generated filename as source

Is there a case where we'd want the developers / users to control what the path in the build context is? I *think* we can abstract that out as an implementation detail here. What do you think?

**Comment by Xarthisius** [comment]
@yuvipanda that's fine with me! I can't think of any possible scenario where the filename inside the docker build context would matter.

**Comment by yuvipanda** [comment]
@Xarthisius awesome! Do ping when you have a PR. ❤️
