### ISSUE TITLE
Resolve remote git references using provider agnostic method

### ISSUE THREAD

**Issue by manics** [jupyter/repo2docker#675]
Follow up from https://discourse.jupyter.org/t/how-to-use-bitbucket-repositories-on-mybinder-org/1000/4

### Proposed change
- Resolve branch names using `git ls-remote` in the bare git provider https://github.com/jupyterhub/binderhub/blob/0b8f99af0a23a7828810b03f010edcefc9a46195/binderhub/repoproviders.py#L126-L160
- Potentially also replace provider specific API calls to resolve branch names

E.g.:
```
git ls-remote https://bitbucket.org/ueacomputervision/image-labelling-tool
f3ddb33e4839f8a0fe73c168993b405adc13daf0        HEAD
8116559e4030d1d4f557617780410cbca7896663        refs/heads/canvas
d50105bacbb74ca139c5bf38ef1657190a006929        refs/heads/group
f3ddb33e4839f8a0fe73c168993b405adc13daf0        refs/heads/master
0b92e511ce8e04f26131efddde9b4a2f5ef9e1e1        refs/heads/multi-user
bc53e6aa12b6d7988de514c8c92e29877be5cc61        refs/heads/separate-modules
a1b2c3bcc2e563afbd335013805d19c95d67224d        refs/heads/server-side-refactor
```
```
$ git ls-remote https://bitbucket.org/ueacomputervision/image-labelling-tool master
f3ddb33e4839f8a0fe73c168993b405adc13daf0        refs/heads/master
```

As indicated in the linked discussion currently the resolution of branch-names to sha1s is done using provider specific API calls, for anything unsupported users must figure out the commit hash themselves.

### Who would use this feature?
Anyone not using GitHub or GitLab.

**Comment by betatim** [comment]
Could you re-open this issue in https://github.com/jupyterhub/binderhub which is where this work needs to happen. Thank you!

**Comment by manics** [comment]
Sorry, had repo2docker on my mind!
https://github.com/jupyterhub/binderhub/issues/843
