### ISSUE TITLE
Allow r2d to work on pre-existing docker images

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#70]
@arokem brought up an interesting idea: that we support building on top of pre-existing docker images. Basically take an image and then add an extra layer of jupyterhub on top so that people can interact with it. @yuvipanda what do you think? We're getting close to outside the scope of r2d, but I could see this being valuable

**Comment by yuvipanda** [comment]
I don't think we have the bandwidth for this unfortunately, and the 'layer of jupyterhub' is just different in different base images that it'll be too much work & not enough actual benefits. We *should* do this as a bunch of docs in z2jh or binder, however. But not here I think.

**Comment by choldgraf** [comment]
ok cool - I think one challenge is that some pre-built images don't have a clear dockerfile (e.g. the original osherman binder image) but some folks might wanna access them through jhub. What do you think about these situations?

**Comment by yuvipanda** [comment]
I think they all need Jesus, not much we can do.

**Comment by yuvipanda** [comment]
Or rather, that's an 'advanced Docker situation' - you can do things like use random from googling to try to get a Dockerfile from a Docker Image. But that's not something we should be providing support for IMO.

**Comment by arokem** [comment]
I respect the bandwidth argument! Just figured that I would chime in here: this (some images just float around without cause, rhyme or reason) is just one reason that docker is the pdf format of scientific reproducibility. Sure, I can read it, but I have no idea how it came about.

**Comment by arokem** [comment]
It also relates to questions I asked over on #62: at some point here jupyterhub gets launched by something, and it's not the Docker image the user supplies. Is this done by r2d? How/where/why?
