### ISSUE TITLE
Document and/or enable logging into a docker image after it's running

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#71]
Is there a way to give people terminal access to a built image that we build with r2d?

**Comment by yuvipanda** [comment]
Locally?

**Comment by choldgraf** [comment]
ya I think so. @arokem can chime in with thoughts too, he asked about it. maybe for debugging?

**Comment by arokem** [comment]
Yes. For example, when you get what I reported on #66

**Comment by willingc** [comment]
Wondering if we can close now. It seems resolved in #66

**Comment by choldgraf** [comment]
I believe this one was actually logging in from the command line. E.g., if the browser connection *doesn't* work, then how can you go inside the container to see what's happening.

It's true that @arokem 's issue was fixed, so maybe we don't want to support manually going inside a container because it should "just work"? I dunno..

**Comment by arokem** [comment]
Yes. That was the issue, but maybe if you consider any condition in which the notebook is inaccessible as terminally broken anyway (forgive the pun 😜) then this would be a condition that never occurs anyway?

**Comment by arokem** [comment]
That is, +1 for closing.

**Comment by choldgraf** [comment]
@yuvipanda and @willingc what do you think? Shall we just say "if your notebook server doesn't launch properly, then something is broken on the r2d side and we want you to file a bug"?
