### ISSUE TITLE
readthedocs broken link to Docker community edition

### ISSUE THREAD

**Issue by johnjarmitage** [jupyter/repo2docker#713]
### Bug description

The link to Docker CE is broken in the installation guide:
https://repo2docker.readthedocs.io/en/latest/install.html
On the line:
"Install Docker as it is required to build Docker images. The Community Edition, is available for free."
the link to the community edition does not work.

It should point to: https://docs.docker.com/install/ or similar

#### Expected behaviour

It should point to: https://docs.docker.com/install/ or similar

#### Actual behaviour

I get a message to say I am "in uncharted waters" :-)

### How to reproduce

1. Go to https://repo2docker.readthedocs.io/en/latest/install.html
2. Click on Community Edition
3. See error

**Comment by betatim** [comment]
Thanks for finding this. I think https://docs.docker.com/install/ is indeed the best place to point people. Do you want to create a PR to fix this?

**Comment by betatim** [comment]
Closed in #715
