### ISSUE TITLE
Single binder directory support

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#72]
We should support specifying binder environment information in a single location that is not used by anything else, a la `.travis.yml` (could be a file or directory), rather than requiring users to fill their repos with potentially several binder-specific files at the top-level that may conflict with files already there. Allowing these to be in top-level `binder.yml` or `binder/` directory would be a big improvement.

Packages may have requirements.txt and/or environment.yml, etc. that describe certain dependencies. To use the same repo on binder, the user may want to have *different* dependencies than the most basic required for the project. As it is now, we are forcing people to make binder-specific *repos* in order to be able to make these choices. It would be nice if this could be done with a single file and/or directory in an existing repo, to avoid conflicting with existing files.

**Comment by choldgraf** [comment]
I'd be +1 for a `.binder/` folder. Agree this is an issue users have ran into.

**Comment by yuvipanda** [comment]
+1 on .binder/ folder rather than file!

**Comment by minrk** [comment]
.binder dir makes sense.
