### ISSUE TITLE
Provide a mechanism for ignoring environment files

### ISSUE THREAD

**Issue by minrk** [jupyter/repo2docker#73]
Since we are following mixed conventions of installation patterns (package.json, requirements.txt, etc.), we need to make sure that it's possible for repos to tell binder *not* to use some of these files, even if they are present.

Repos may have multiple of these files that should be considered mutually exclusive (e.g. requirements.txt and environment.yml to serve both pip and conda users, or `package.json` that's only part of a build step, and binder should ignore it, or a Dockerfile for standalone running/testing that shouldn't be used on binder). We should make sure that there is a way for users to tell binder what to do, regardless of the presence of top-level dependency files that binder should ignore.

This is related to #72, where the presence of a `/binder` directory or `binder.yml` file could prevent looking at any top-level files (for instance).

**Comment by choldgraf** [comment]
I think we can close this now that we support `binder` folders, yeah?

**Comment by willingc** [comment]
I'm going to close as binder-examples and #165 have done a bunch to improve this issue. @minrk please reopen if there is a next step that I've missed here. Thanks.
