### ISSUE TITLE
Binderhub unable to access private repo with git-credential-env 

### ISSUE THREAD

**Issue by eexwhyzee** [jupyter/repo2docker#736]
### Bug description

When running binderhub with repo2docker, binderhub is unable to clone from a private repo.

#### Expected behaviour

Binderhub should be able to clone from a private repo and start building the image.

#### Actual behaviour

<img width="729" alt="Screen Shot 2019-07-09 at 10 02 41 AM" src="https://user-images.githubusercontent.com/13672394/60908729-6c903c80-a231-11e9-99f1-6269b7b0c6b0.png">

### How to reproduce

1. Deploy binderhub using 0.2.0-c8ab0a3 with repo2docker a251ad26 w/ a github access token
2. Try to create a new binder using a link to a private github repo
3. Build will fail with error above

### Your personal set up

 - OS: macOS 10.13.6
 - Docker version: Docker version 18.09.2, build 6247962
 - repo2docker version: image tag a251ad26
 - binderhub version: 0.2.0-c8ab0a3

Github section of my `secrets.yaml`:
```
config:
  GitHubRepoProvider:
    access_token: ****
```
Access token has the proper permissions:
<img width="730" alt="Screen Shot 2019-07-08 at 3 23 57 PM" src="https://user-images.githubusercontent.com/13672394/60909157-66e72680-a232-11e9-804c-0fcbfe782329.png">

### Workaround
I was able to narrow down the cause of the issue to a git install change in the `Dockerfile`: https://github.com/jupyter/repo2docker/commit/ee93bcf1a6155a71c8978b78b8bf03282dbdf088#diff-3254677a7917c6c01f55212f86c57fbf

I reverted this change to the `Dockerfile` (used `python:3.7` instead of `alpine`) and built the image locally to use for my binderhub deployment and was able to successfully clone and build from a private github repo.

**Comment by betatim** [comment]
Thanks for finding this bug and the excellent bug report!

Do you know what exactly the new `apt-get install` command/setup does in the commit you linked to? My guess would be that we now install an older version of git or an otherwise broken version? Unfortunately I don't know enough about the Ubuntu/Debian package management system to have an idea off the top of my head. If you have time and/or knowledge to investigate or suggest a fix that would be great and if not that is (of course!) also fine.

**Comment by eexwhyzee** [comment]
@betatim I'm also unsure what exactly is going on but I can investigate some more, guessing that the version of git that is being installed doesn't have the credential helpers. Also to note that the latest repo2docker `Dockerfile` being used is based off the `alpine` image, the one I got working locally is based off `python:3.7`

**Comment by eexwhyzee** [comment]
@betatim alright i figured out what's going on, the `git-credential-env` file requires [bash](https://github.com/jupyter/repo2docker/blob/master/docker/git-credential-env#L1), and the new repo2docker `Dockerfile` is based on `alpine` which doesn't come with bash by default, I confirmed that adding bash installation to the existing `Dockerfile` fixes the bug (adds ~5MB to the image)

**Comment by betatim** [comment]
Very cool. Do you want to make a PR that add bash back?

The motivation for using `alpine` was to make the repo2docker image itself smaller and I think I remember it shrinking by more than 5MB that we'd have to pay to put bash back. So that seems like the right fix.

**Comment by eexwhyzee** [comment]
yeah that sounds good to me as well, I'll have a PR out sometime today
