### ISSUE TITLE
Could not find a kernel matching Julia 1.1.1

### ISSUE THREAD

**Issue by janlisse** [jupyter/repo2docker#763]
### Bug description
When i launch my Julia notebook from https://github.com/JuliaEnergy/PowerDynamicsExamples/blob/master/ieee14-minimal/runexample.ipynb
on mybinder.org the container builds fine but during launch i get the error message:
`Could not find a kernel matching Julia 1.1.1`

#### Expected behaviour
The notebook should launch with a Julia 1.1.1 kernel

#### Actual behaviour
I get the above error message and i can't manually select a Julia kernel, only Python 3.

### How to reproduce
Launch notebook on binder:
https://mybinder.org/v2/gh/JuliaEnergy/PowerDynamicsExamples/master?filepath=ieee14-minimal%2Frunexample.ipynb

**Comment by betatim** [comment]
Your repository doesn't contain a file that triggers the inclusion of Julia support.

Please take a look at the Julia example https://github.com/binder-examples/demo-julia and the possible supported config files https://repo2docker.readthedocs.io/en/latest/config_files.html

**Comment by janlisse** [comment]
Under the subdirectory "ieee14-minimal" which is included in the binder link i have a "Project.toml"
That should trigger the Julia build, shouldn't it?
When i run repo2docker locally:
```jupyter-repo2docker --subdir ieee14-minimal https://github.com/JuliaEnergy/PowerDynamicsExamples```
I can see that the Julia build is triggered properly.

**Comment by betatim** [comment]
>  That should trigger the Julia build, shouldn't it?

It has to be in the top level directory or a `binder/` subdirectory. The `--subdir` flag is not used when the repository is launched on a BinderHub.

**Comment by janlisse** [comment]
Means that it is not possible to have a single git repo with multiple Julia projects and separate Project.toml files and generate binder links for each of them?

**Comment by betatim** [comment]
Correct.

**Comment by janlisse** [comment]
Yes sure, thx for your help!
