### ISSUE TITLE
Error on `--push`

### ISSUE THREAD

**Issue by arokem** [jupyter/repo2docker#801]
### Bug description
I am seeing the following: 

```
(hcp-pangeo-docker) hcp-pangeo-docker (master)$jupyter-repo2docker --push .
Picked Local content provider.
Using local repo ..
Using DockerBuildPack builder
Step 1/1 : from pangeo/base-notebook-onbuild
# Executing 6 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Running in fecb5513ee18
Removing intermediate container fecb5513ee18
 ---> 089fef3e5973
{"aux": {"ID": "sha256:089fef3e5973580b76ba2e0f80ecf52002520f47a2d74d179b436123934ad937"}}[Warning] One or more build-args [NB_USER NB_UID] were not consumed
Successfully built 089fef3e5973
Successfully tagged r2d-2e1569706729:latest
Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/bin/jupyter-repo2docker", line 10, in <module>
    sys.exit(main())
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/__main__.py", line 354, in main
    r2d.start()
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/app.py", line 717, in start
    self.push_image()
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/app.py", line 459, in push_image
    progress = json.loads(line.decode("utf-8"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 64)
```

#### Expected behaviour

I thought this would push the built image to dockerhub (or somewhere else? Not sure how I would control that)

#### Actual behaviour

See above. 

### How to reproduce

Not sure. The repo for the Docker config in that folder is here: https://github.com/nrdg/hcp-pangeo-docker

repo2docker was installed into a new virtualenv, using `pip install jupyter-repo2docker` and 

```
(hcp-pangeo-docker) hcp-pangeo-docker (master)$docker --version
Docker version 19.03.2, build 6a30dfc
```

### Your personal set up

 - OS: Mac OSX
 - Docker version: See above
 - repo2docker version 0.10.0

**Comment by betatim** [comment]
It should do the same thing as `docker push <imagename>` does. Could you check that that command works?

The error looks like there is some text arriving which isn't JSON where repo2docker thinks it should be receiving JSON. It would help a lot with debugging if you could go to `/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/app.py` line 459 and capture the value of `line` in the run up to the exception.

**Comment by arokem** [comment]
Thanks for the suggestions!

`docker push r2d-2e1569849176` produces: 

```
hcp-pangeo-docker) hcp-pangeo-docker (master)$docker push r2d-2e1569849176
The push refers to repository [docker.io/library/r2d-2e1569849176]
b105c35b6e05: Preparing 
...
a1aa3da2a80a: Waiting 
denied: requested access to the resource is denied
```
Even though I am logged in (I believe!). So this might somehow be the underlying cause of this?

In addition, adding a `print(line)` in the place you mentioned produces: 

```
(hcp-pangeo-docker) hcp-pangeo-docker (master)$jupyter-repo2docker --push .
Picked Local content provider.
Using local repo ..
Using DockerBuildPack builder
Step 1/1 : from pangeo/base-notebook-onbuild
# Executing 6 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Running in 95644f4cd2b8
Removing intermediate container 95644f4cd2b8
 ---> 971664e8377b
{"aux": {"ID": "sha256:971664e8377bac3183f691be8218a616c0825151c5854d672e2c5fac94cd9003"}}[Warning] One or more build-args [NB_USER NB_UID] were not consumed
Successfully built 971664e8377b
Successfully tagged r2d-2e1569849427:latest
b'{"status":"The push refers to repository [docker.io/library/r2d-2e1569849427]"}\r\n'
b'{"status":"Preparing","progressDetail":{},"id":"b105c35b6e05"}\r\n'
b'{"status":"Preparing","progressDetail":{},"id":"ee0732a81434"}\r\n{"status":"Preparing","progressDetail":{},"id":"ab0efea628d6"}\r\n{"status":"Preparing","progressDetail":{},"id":"21c42824a566"}\r\n{"status":"Preparing","progressDetail":{},"id":"d95916eb821f"}\r\n{"status":"Preparing","progressDetail":{},"id":"15144d777cd6"}\r\n{"status":"Preparing","progressDetail":{},"id":"57df8f055e5c"}\r\n{"status":"Preparing","progressDetail":{},"id":"dfc4b20b9f55"}\r\n{"status":"Preparing","progressDetail":{},"id":"d74a0c892c16"}\r\n'
Traceback (most recent call last):
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/bin/jupyter-repo2docker", line 10, in <module>
    sys.exit(main())
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/__main__.py", line 354, in main
    r2d.start()
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/app.py", line 718, in start
    self.push_image()
  File "/Users/arokem/.virtualenvs/hcp-pangeo-docker/lib/python3.7/site-packages/repo2docker/app.py", line 460, in push_image
    progress = json.loads(line.decode("utf-8"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 64)
(hcp-pangeo-docker) hcp-pangeo-docker (master)$
```

Does that help diagnose this?

**Comment by betatim** [comment]
Sounds like there are two problems. 

1) we don't consider the case where there are multiple JSON messages in one `line` (there are `\r\n` characters there that indicate line breaks)
2) you can't push to docker hub, but that might be because for the `docker push` command we have to prefix the image name with your username

**Comment by betatim** [comment]
Looking at the code on master I found https://github.com/jupyter/repo2docker/blob/27eeef2c9728fc3437e8e69e64e3b258336c5fb5/repo2docker/app.py#L466-L469 which makes me think we already found and fixed this a while ago. Can you try running the latest `master` instead of v0.10.0?

`pip install --upgrade https://github.com/jupyter/repo2docker/archive/master.zip`  should install the latest version.

**Comment by arokem** [comment]
Yes! I no longer get the JSON error. 

I do still get `denied: requested access to the resource is denied` at the end of it all.

I also tried `docker push arokem/r2d-2e156993074`

After the build is done. But then I get: 

`An image does not exist locally with the tag: arokem/r2d-2e156993074`

I think that you are correct that the push needs to be prefixed with my user-name, but the image also needs to be built with my user-name as a prefix.

**Comment by betatim** [comment]
I think to create a new tag with the username first something like `docker tag r2d-2e156993074 arokem/r2d-2e156993074` will create a new tag that you can then push.

Thanks for filing the issue and following up!
