### ISSUE TITLE
Legacy buildpack tests are failing in travis

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#828]
In recent pull requests, we discovered that there are tests failing for the legacy build packs. For example, see this travis output:

https://travis-ci.org/jupyter/repo2docker/jobs/622090584?utm_medium=notification&utm_source=github_status

We should figure out why this is happening.

Alternatively, perhaps we can consider deprecating legacy repositories? I'm not sure what's different, but if this is purely a matter of allowing "old-style binder repositories" to work, then maybe enough time has passed that we can have a 1- or 2-month deprecation warning somewhere, and then remove those buildpacks?

**Comment by betatim** [comment]
I made one attempt at fixing it by updating the version of conda but now the build just hangs (on my laptop).

I don't fully understand what/who changed :-/

The error suggests that the environment will end up not having the `conda` executable installed any more, but the inputs to the environment specification haven't changed. Very confusing.

**Comment by betatim** [comment]
In terms of deprecating the legacy buildpack: I don't know how many repos still use it successfully.

Anecdotally I see it used once in a while but "often" the build of that particular repo is broken.

Maybe the way forward is to change this build pack so that it prints instructions for how to convert your repository to a new build pack as a way of phasing it out.

**Comment by choldgraf** [comment]
I think I'd be +1 on hard-deprecating the legacy buildpack, rather than digging into andrewosh's docker image to figure out what kind of weird dependency issue is going on. Could we do something like:

* Find (or create) a page on "migrating from legacy Dockerfiles"
* Modify r2d so that the legacy buildpack errors with an informative message and a link to that page for instructions?

I think it's a bit abrupt, but then again:

1. It has been called "legacy" for about 2 years now
2. It will only affect new *builds* of repositories, not pre-existing images that have already been built (e.g. if somebody tagged a repo)
3. If a user *really* wanted to use the legacy dockerfile, they could use their own (older) version of repo2docker

what do you think?
