### ISSUE TITLE
Start RStudio when conda environment contains R packages

### ISSUE THREAD

**Issue by xhochy** [jupyter/repo2docker#837]
### Proposed change

If the user provides an `environment.yml` file that contains an R package, we should also start RStudio via `jupyter_server_proxy`. For the start, we could determine the usage of R by checking if any of the dependencies in the `environment.yml` contains an `r-` prefix.

### Who would use this feature?

This would be used by people that install their R packages via `conda` as well as could it be an [alternative to MRAN](https://github.com/jupyter/repo2docker/issues/773) to get pinned versions for R packages.

### How much effort will adding it take?

This needs a bit of refactoring to expose the install commands for RStudio separately from the `RBuildPack`. Otherwise, the work will be limited to testing the setup.

### Who can do this work?

I happy to implement this incl. an example for binder.

**Comment by betatim** [comment]
This is super cool!
