### ISSUE TITLE
Release new version to make jupyterlab@0.27.0 available to binderhub

### ISSUE THREAD

**Issue by gnestor** [jupyter/repo2docker#84]
Follow up from https://github.com/jupyter/repo2docker/pull/80

**Comment by yuvipanda** [comment]
is done now! New builds will have a newer version of JupyterLab in them!

**Comment by yuvipanda** [comment]
We had to revert that deploy due to unrelated issues, unfortunately. Will take another shot tomorrow!

**Comment by gnestor** [comment]
Any news on this today?

**Comment by choldgraf** [comment]
Latest version should be deployed now! Can you give it a shot?
--

**Comment by gnestor** [comment]
It's working: https://hub.beta.mybinder.org/user/gnestor-jupyter-renderers-ayiegz1o/lab

Thanks @choldgraf and @yuvipanda!!

**Comment by choldgraf** [comment]
@gnestor can you share a binder link? That's a private link for your pod, and isn't shareable.

I'll build an example repository in `binder-examples` once I see how your repo is structured!

**Comment by gnestor** [comment]
https://beta.mybinder.org/v2/gh/jupyterlab/jupyter-renderers/master

**Comment by choldgraf** [comment]
woot! see https://github.com/binder-examples/jupyterlab for an example repo inspired by your repo

**Comment by gnestor** [comment]
Excellent!!
