### ISSUE TITLE
Failures to install readtext package 

### ISSUE THREAD

**Issue by zwguo95** [jupyter/repo2docker#843]
Hi,

I cannot install readtext package on binder. Here's part of the error message -- 

Configuration failed because poppler-cpp was not found. Try installing:
 * deb: libpoppler-cpp-dev (Debian, Ubuntu, etc)
 * On Ubuntu 16.04 or 18.04 use this PPA:
    sudo add-apt-repository -y ppa:cran/poppler
    sudo apt-get update
    sudo sudo apt-get install -y libpoppler-cpp-dev
 * rpm: poppler-cpp-devel (Fedora, CentOS, RHEL)
 * csw: poppler_dev (Solaris)
 * brew: poppler (Mac OSX)
If poppler-cpp is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a poppler-cpp.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'

**Comment by betatim** [comment]
For support questions it is better to open a new thread on the [community forum](https://discourse.jupyter.org). There are more people there so higher chance of someone knowing the answer and it is better indexed by google which increases the chances of future generations finding the answer.

The other thing to post that will increase the chances of getting a good answer is a link to a repository that we can use to reproduce this error.

My proposal: create a post in the forum with your message above and a link.
