### ISSUE TITLE
RShiny bus-dashboard example returns 500

### ISSUE THREAD

**Issue by supern8ent** [jupyter/repo2docker#852]
### Bug description

Running [RShiny bus-dashboard example](https://github.com/binder-examples/r) with repo2docker is timing out and reporting "500 : internal server error" on loading.

#### Expected behaviour

`jupyter-repo2docker rshiny-bus` builds a container and runs it.  
Visiting `http://127.0.0.1:<port>?token=<token>` in browser brings you to Jupyter.  
Visiting `http://127.0.0.1:<port>/shiny/bus-dashboard` runs the example shiny app.  

#### Actual behaviour

Visiting `http://127.0.0.1:<port>/shiny/bus-dashboard` reports "500 : internal server error".  
In the console this traceback is logged:

    [E 00:31:47.512 NotebookApp] Uncaught exception GET /shiny/bus-dashboard (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:49558', method='GET', uri='/shiny/bus-dashboard', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 94, in get
        return await self.http_get(*args, **kwargs)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 391, in http_get
        return await self.proxy(self.port, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 387, in proxy
        return await super().proxy(self.port, path)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 209, in proxy
        response = await client.fetch(req, raise_error=False)
    tornado.simple_httpclient.HTTPTimeoutError: Timeout during request

### Your personal set up

 - OS: OSX
 - Docker version 19.03.5
 - repo2docker version repo2docker version 0.11.0

**Comment by manics** [comment]
This is working for me with the latest repo2docker (master), and also works on mybinder (https://mybinder.org/v2/gh/binder-examples/r/master) if you go through the `New` menu. However if I remove the trailing `/` I get an error.

Does adding the trailing `/` to `http://127.0.0.1:<port>/shiny/bus-dashboard/` work for you?

**Comment by supern8ent** [comment]
No, it also fails with the trailing slash.

**Comment by supern8ent** [comment]
This just got weird. 

- Works in Chrome
- Works in Firefox private window
- Works in Firefox regular window if I change 127.0.0.1 to localhost (have to enter the token)
- Fails in Firefox regular window
- Fails in Firefox regular window with all add-ons disabled

Here is a screenshot of the console when it fails in Firefox regular window
![image](https://user-images.githubusercontent.com/10649212/75580140-15d3af00-5a1c-11ea-98fb-cc264f2e5bc1.png)

**Comment by manics** [comment]
This sounds like a caching issue, especially since it works with `localhost` but not `127.0.0.1`. Could you try clearing your cache for that site? In Firefox history search for `127.0.0.1`, right click, `Forget About This Site`.

**Comment by supern8ent** [comment]
Yup, clearing the cache got it working. Thank you so much!
