### ISSUE TITLE
--env option semantics differ from docker's

### ISSUE THREAD

**Issue by hwine** [jupyter/repo2docker#871]
### Bug description
The semantics for the `--env` option to `repo2docker` differs from the sane option in the `docker run` subcommand.

#### Expected behaviour

I expected the option to behave identically, but they do not in the case of a bare environment variable name. For example, to pass the value of a secret to a docker instance (so it does not appear on the command line), you can do:
```bash
SEKRT=fred  docker run --env SEKRT ...
```
and the value of `SEKRT` inside the container is "fred".

see also [docker documentation](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)

#### Actual behaviour

For `repo2docker`:
```bash
SEKRT=fred  repo2docker --env SEKRT ...
```
and `SEKRT` is undefined inside the container.
### How to reproduce

1. Download [this notebook](https://gist.github.com/34dd525848df78a5adc101b0da0ac3eb) to an empty directory
2. run `SEKRT=sam repo2docker --env SEKRT -E .`
    1. connect to server and run notebook cells
    1. note output -- this is observed
    1. stop server
3. Get docker image just created: `image=$(docker images --quiet | head -1)`
1. run `SEKRT=sam docker run --rm --env SEKRT $image`
    1. connect to server and run notebook cells
    1. note output -- this is expected
    1. stop server

### Your personal set up

 - OS: Ubuntu Ubuntu 18.04.4 LTS
 - Docker version: 18.06.1-ce, build e68fc7a
 - repo2docker version: 0.11.0

**Comment by betatim** [comment]
Thanks a lot for reporting this. I never realised that there was `--env NAME_OF_EXISTING_VAR` for docker run. I've only ever used `--env FOO=BAR`.

Right now the arguments passed to `--env` are passed right through to here:

https://github.com/jupyter/repo2docker/blob/1bb0c07bf184e6042c362e59602688bb3cb2241e/repo2docker/app.py#L563-L574

We'd need to add some processing/logic to detect values without a `=` in them, look up their value and then add them back to the list.

I think this would be a good addition to have. Do you want to/have time to work on a PR for this?

**Comment by hwine** [comment]
Sure -- let me give it a shot.
