### ISSUE TITLE
failing docker tests locally on macOS (case 1)

### ISSUE THREAD

**Issue by hwine** [jupyter/repo2docker#881]
### Bug description

With the latest versions of macOS (Catalina 10.15.4) and Docker CE (2.2.0.5), many of the tests fail to run locally.

#### Expected behaviour

Running the test suite locally on a released version of `repo2docker` should have no errors or failures.

#### Actual behaviour

A number of tests which require running docker fail. The displayed message indicates Docker was unable to complete a volume mount:
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Mounts denied: 
The path /var/folders/fs/fjwjlc5x3yzgbw2nnnyzfcq80000gn/T/tmpxb7ynwyc
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.")
```
Following the Docker instructions to add the path to the list of allowed mounting paths does not change the behavior.

### How to reproduce

1. On a macOS box, checkout a released version of `repo2docker`
2. Setup the development environment.
3. invoke `pytest tests/unit/test_env.py` (as one example)
4. observe failure.

### Your personal set up

 - OS: macOS
 - Docker version: CE 2.2.0.5
 - repo2docker version: 0.11.4

### Workaround

While this is clearly a Docker problem, it is possible to tweak (some of) the tests to avoid needing to use the problematic directory paths.

For example, in the `test_env.py` shown above, `repo2docker` is invoked from a directory that both:
- is created in a manner that ensures the directory will be deleted at the end of the test (unless python itself crashes)
- has no content

Thus, changing the parent of the temp directory to be the git working directory allows the test to pass:
```diff
-    with tempfile.TemporaryDirectory() as tmpdir:
+    # There appear to be some odd combinations of default dir that do
+    # not work on macOS Catalina with Docker CE 2.2.0.5, so use
+    # the current dir -- it'll be deleted immediately
+
+    with tempfile.TemporaryDirectory(dir=os.path.abspath(os.curdir)) as tmpdir:
```

This approach may not be applicable for all such locations, or desired for other reasons by the team. I'm happy to prepare a PR if project folks think this is a reasonable approach.

**Comment by betatim** [comment]
I don't think there is a reason for using the default temporary directory over the directory of the repository. (Should it be `os.curdir` or the [`HERE = abspath(__file__)`](https://github.com/jupyter/repo2docker/blob/356ea1086868d36fdfd5be2e0d21fc4dae33b060/repo2docker/buildpacks/conda/freeze.py#L27) style incantation?)

A PR would be great.

I didn't even know `TemporaryDirectory()` had a `dir` option! A reminder to once in a while read the docs of tools you've been using for years 😃 It is great when you learn something new from issues!

**Comment by hwine** [comment]
Here's a list of test files that invoke TemporaryDirectory. I'll use this as a punch list.

- [ ] tests/conftest.py
- [ ] tests/unit/test_freeze.py
- [ ] tests/unit/test_volumes.py
- [ ] tests/unit/test_env.py
- [ ] tests/unit/test_buildpack.py
- [ ] tests/unit/test_users.py
- [ ] tests/unit/test_ports.py
- [ ] tests/unit/test_clone_depth.py
- [ ] tests/unit/test_app.py
- [ ] tests/unit/contentproviders/test_figshare.py
- [ ] tests/unit/contentproviders/test_hydroshare.py
- [ ] tests/unit/contentproviders/test_git.py
- [ ] tests/unit/contentproviders/test_zenodo.py
- [ ] tests/unit/contentproviders/test_local.py
- [ ] tests/unit/contentproviders/test_dataverse.py

**Comment by betatim** [comment]
Do you have advice/opinion on changing tests that use a temporary directory but don't mount it? My first instinct would be to leave them unchanged.

What do you think of merging #882 once it fixes the `test_env.py` test? when looking at the above list I thought that it is long and that #882 is already (when not WIP any more) strictly better than what we have now so we could merge it. I am easy either way.

**Comment by hwine** [comment]
> Do you have advice/opinion on changing tests that use a temporary directory but don't mount it? My first instinct would be to leave them unchanged.

Agreed. When I noticed that, I realized my initial assumption was wrong 😬. I haven't yet had time to investigate what is really happening.

> What do you think of merging #882 once it fixes the `test_env.py` test? when looking at the above list I thought that it is long and that #882 is already (when not WIP any more) strictly better than what we have now so we could merge it. I am easy either way.

Good idea! ("Perfection is the enemy of done!") Since all the other appear to have a different cause, it doesn't make sense to hold this one up.
