### ISSUE TITLE
Missing ":" in docs for R DESCRIPTION

### ISSUE THREAD

**Issue by adamhsparks** [jupyter/repo2docker#898]
### Bug description
Missing ":" in documentation

Here, https://github.com/jupyter/repo2docker/blob/81090b0f457695a2843632ae8d763ff5404e2a3e/docs/source/config_files.rst#L145

`devtools:install_git(".")` should be `devtools::install_git(".")`

**Comment by betatim** [comment]
Thanks! Do you want to make a PR to fix it?

**Comment by adamhsparks** [comment]
can do
