### ISSUE TITLE
Support non-GitHub git repo hosts

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#96]
There are a bunch of other hosts out there other than vanilla github repositories. We should support most of these eventually!

Some that come to mind:

- [ ] GitLab
- [ ] GitHub gists
- [ ] bitbucket
- [ ] osf.io

**Comment by betatim** [comment]
For GitLab instances a URL like https://gitlab.com/<user>/<repo>.git should work (for example the USGS instance https://code.usgs.gov/usgs/whcmsc-rdc).

I'd add osf.io to the list of sources

**Comment by betatim** [comment]
I think `repo2docker` itself would "just work" with any git repository as you pass it a URL. That means to enable other git based hosts it is binderhub that needs working on. For hosts that aren't git based: should we add "general purpose file downloading" to repo2docker or a new tool or...?

**Comment by rsignell-usgs** [comment]
This would be a great boost for us to promote Binder here at USGS.

**Comment by yuvipanda** [comment]
repo2docker doesn't know anything about GitHub. This needs to be in binderhub, which has the concept of 'providers'. We currently only implement a GitHub provider, but implementing a gitlab provider should be pretty easy.

**Comment by choldgraf** [comment]
@yuvipanda shall I close this issue and open it in binderhub?

**Comment by yuvipanda** [comment]
@choldgraf yup!

**Comment by choldgraf** [comment]
opened: https://github.com/jupyterhub/binderhub/issues/184
